Daily-DAYO/DAYO_Android

app/src/main/java/com/daily/dayo/follow/FollowFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowingListFragment.kt, app/src/main/res/drawable/edittext_background_follow_search.xml, app/src/main/res/layout/fragment_follow.xml, app/src/main/res/layout/fragment_follower_list.xml, app/src/main/res/layout/fragment_following_list.xml, app/src/main/res/layout/fragment_my_profile.xml, app/src/main/res/layout/fragment_other_profile.xml, app/src/main/res/layout/item_follow.xml, app/src/main/res/navigation/nav_graph.xml
+ FollowFragment 레이아웃 구현
+ MyProfileFragment, OtherProfileFragment의 카운트 부분 레이아웃 변경
resolved: #18
=> #18 [layout] FollowFragment, MyProfileFragment, OtherProfileFragment

app/src/main/java/com/daily/dayo/feed/FeedFragment.kt, app/src/main/res/drawable/selector_button_search_recommend_keyword.xml, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_other_profile.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/item_search_recommend_keyword.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
* 검색어 입력 디자인 추가에 따른 레이아웃 수정
* 추천 검색어 아이템 디자인 수정
resolved: #17
=> #17 [layout] SearchFragment Keyword Input

app/build.gradle, app/src/main/java/com/daily/dayo/FolderAddFragment.kt, app/src/main/java/com/daily/dayo/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowingListFragment.kt, app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/home/NewPostListFragment.kt, app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/util/AutoClearedValue.kt, app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/write/WriteTagFragment.kt
- Memory Leak 방지를 위한 Viewbinding 사용 시 AutoClearedValue를 활용하도록 적용
resolved: #35
=> #35 [refactoring] AutoClearedValue Apply

app/build.gradle
- 원활한 Library 사용을 위한 Dependencies Version 업데이트
resolved: #37
=> #37 [refactoring] Dependencies Version Update

app/build.gradle, app/src/main/AndroidManifest.xml
- Jetpack Compose 사용을 위한 Build.gradle에 Compose 추가 및 영향 받는 설정 부분 수정
resolved: #39
=> #39 [refactoring] Apply Jetpack Compose

build.gradle
- Kotlin Plugin Version 1.5.0 -> 1.6.0 으로 업데이트
resolved: #41
=> #41 [refactoring] Kotlin Version Update

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/DayoApplication.kt, app/src/main/java/com/daily/dayo/MainActivity.kt, app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/home/NewPostListFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapater.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/res/layout/item_main_post.xml, build.gradle
**Request할 Feature**
- Retrofit2, OkHttp, Hilt 사용을 위한 build.gradle 추가 및 영향 받는 부분 추가
- HomeFragment Adapter 수정
resolved: #47
=> #47 [feature] Retrofit2, OkHttp, Hilt, HomeFragment Adapter

app/build.gradle, build.gradle
- Compose 미사용 및 1.6.0 버전 미지원으로 인한 compose 사용 비활성화
resolved: #49
=> #49 [bug] Disable Compose

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/di/NetworkModule.kt, app/src/main/java/com/daily/dayo/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt, app/src/main/java/com/daily/dayo/repository/HomeRepository.kt, app/src/main/java/com/daily/dayo/util/Resource.kt, app/src/main/java/com/daily/dayo/util/Status.kt
**Request할 Feature**
- Retrofit2, Hilt, Coroutine등을 활용하여 MVVM 패턴을 적용한 Network 구성
- DayoPickPostListFragment에 대한 네트워크 연결 구성
resolved: #54
=> #54 [feature] Network Setting, DayoPickPostListFragment

app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/res/layout/fragment_write.xml
- 글 작성 화면에서 선택한 다이어리 분류 라디오 버튼 값 전달 적용
- layout 파일 카테고리 component 오탈자 수정
resolved: #56
=> #56 [feature] WriteFragment RadioButton Value

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/write/WriteTagFragment.kt, app/src/main/res/layout/fragment_write_option.xml, app/src/main/res/layout/fragment_write_tag.xml, app/src/main/res/layout/item_write_post_tag_chip.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml, build.gradle
- AnroidManifest.xml 중복 line 제거]
- 태그 추가 기능 구현
- WriteTagFragment에서 Tag List를 RecyclerView에서 ChipGroup으로 변경
- ChipGroup 사용에 따른 chip Layout 구성
- 추가한 태그에 대하여 확인을 누르면 이전 화면으로 돌아가면서 추가한 태그 값 넘겨주는 기능 구현
- Fragment간 Navigation을 사용하여 데이터 전달을 위한 Safe Args추가
- Safe Arg를 활용한 Fragment간 PostTagList Data 전달 구현
- WriteOptionFragment에서 작성한 postTagList를 보여주는 TextView에 대해 Line Break 적용
resolved: #58
=> #58 [feature] passing the data about postTagList in Write

app/src/main/java/com/daily/dayo/login/LoginActivity.kt
+ 로그인 성공 후 MainActivity로 전환 시 Intent Flag를 추가하여 LoginActivity 스택 제거
resolved: #61
=> #61 [bug] LoginActivity to MainActivity

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/res/layout/item_main_post.xml
=> #68 [feature] DayoPickPostListFragment, ResponsePostModel

app/src/main/java/com/daily/dayo/di/NetworkModule.kt
* retrofit요청 시 ScalarsConverterFactory 추가
resolved: #73
=> #73 [bug] Remove double quotes

app/src/main/java/com/daily/dayo/util/DefaultDialog.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/res/drawable/dialog_alert_default.xml, app/src/main/res/drawable/ic_alert.xml, app/src/main/res/layout/dialog_default_alert.xml, app/src/main/res/values/strings.xml
**Layout 변경 사항**
resolved: #78
=> #78 [layout] DefaultDialogAlert

app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/MyProfileFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Folder.kt, app/src/main/java/com/daily/dayo/profile/model/ResponseFolder.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/FolderRepository.kt, app/src/main/res/layout/fragment_profile_folder_list.xml, app/src/main/res/layout/item_profile_folder.xml
=> #81 [feature] ProfileFolderListFragment

app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt, app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteFolderAdapter.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteUploadImageListAdapter.kt, app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderAddViewModel.kt, app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderViewModel.kt, app/src/main/res/layout/fragment_write_folder.xml, app/src/main/res/layout/item_folder_list.xml
+  게시글 작성 > 폴더 선택 시 폴더 리스트 조회 구현
=> #81 [feature] WriteFolderFragment

app/src/main/java/com/daily/dayo/profile/FolderSettingFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/FolderSettingAdapter.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderSettingViewModel.kt, app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt
+ 마이페이지 > 폴더 설정 시 폴더 리스트 조회 구현
resolved: #81
=> #81 [layout] FolderSettingFragment

app/src/main/java/com/daily/dayo/network/Post/PostApiHelper.kt, app/src/main/java/com/daily/dayo/network/Post/PostApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/Post/PostApiService.kt, app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt, app/src/main/java/com/daily/dayo/post/model/PostComment.kt, app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt, app/src/main/java/com/daily/dayo/repository/PostRepository.kt, app/src/main/res/layout/item_post_comment.xml
- 특정 게시글에 대한 댓글 작성 기능 구현
- 작성된 댓글에 대한 조회 기능 구현
- 댓글 작성 직후 댓글 창 맨 아래로 이동 기능 구현
resolved: #98
=> #98 [feature] Write Comment, Read Comment List

app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileBookmarkPostListFragment.kt, app/src/main/res/layout/fragment_my_profile.xml, app/src/main/res/layout/fragment_profile_bookmark_post_list.xml
- 북마크 페이지 탭 추가
- ProfileBookmarkPostListFragment 추가
- 사용자 이메일 표시 추가 
- 기타 레이아웃 변경 반영 **(옵션 창 제외)**
- 서버와 연동하여 MyProfile정보 표시
resolved: #104
=> #104 [layout] MyProfileFragment

app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt, app/src/main/java/com/daily/dayo/profile/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/profile/model/Folder.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderSettingViewModel.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/FolderRepository.kt, app/src/main/java/com/daily/dayo/write/WriteFolderAddFragment.kt, app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteFolderAdapter.kt, app/src/main/java/com/daily/dayo/write/viewmodel/WriteFolderViewModel.kt, app/src/main/res/layout/fragment_folder_setting_add.xml, app/src/main/res/layout/item_profile_folder.xml, app/src/main/res/values/themes.xml
+ 프로필 > 폴더 설정 > 폴더추가 페이지 기능 구현
+  API변경사항에 따라 폴더 추가 기능 수정
resolved: #102
=> #102 [feature] FolderSettingAddFragment, WriteFolderAddFragment

app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt, app/src/main/java/com/daily/dayo/profile/FolderFragment.kt, app/src/main/java/com/daily/dayo/profile/FolderOptionFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Folder.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderOptionViewModel.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderViewModel.kt, app/src/main/java/com/daily/dayo/repository/FolderRepository.kt, app/src/main/java/com/daily/dayo/util/DefaultDialog.kt, app/src/main/res/drawable/ic_option_horizontal_white.xml, app/src/main/res/layout/dialog_defalt_explanation_confirm.xml, app/src/main/res/layout/fragment_folder.xml, app/src/main/res/layout/fragment_folder_option.xml, app/src/main/res/layout/item_folder_post.xml, app/src/main/res/layout/item_profile_folder.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
+ 각 폴더의 세부 정보페이지 생성
+ 폴더에 해당하는 게시글 대표 이미지 보여주기
+ FolderOptionFragment 생성
+ 폴더 삭제 기능 구현
+ DefaultDialog에 설명글이 포함되어있는 템플릿 추가 
+ DefaultDialogExplanationConfirm
resolved: #97
=> #97 [feature] FolderFragment, FolderOptionFragment

app/src/main/java/com/daily/dayo/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/OtherProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Profile.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/OtherProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt, app/src/main/res/drawable/selector_button_follow.xml, app/src/main/res/drawable/selector_button_follow_text.xml, app/src/main/res/layout/fragment_my_profile.xml, app/src/main/res/layout/fragment_other_profile.xml, app/src/main/res/layout/item_follow.xml, app/src/main/res/navigation/nav_graph.xml
+ 다른사람의 프로필 확인 시 나타나는 페이지 구현
+ 프로필 정보 API 연동
+ 폴더 리스트 띄우기
+ 마이페이지 정보 API 연동
+ 마이페이지, 다른사람프로필에서 폴더 리스트 아이템 클릭 시 해당 폴더페이지로 이동 구현
resolved : #113
=> [feature] OtherProfileFragment

app/src/main/java/com/daily/dayo/login/LoginActivity.kt, app/src/main/java/com/daily/dayo/login/LoginFragment.kt, app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordConfirmationFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/util/ButtonActivation.kt, app/src/main/java/com/daily/dayo/util/HideKeyBoardUtil.kt, app/src/main/res/drawable/button_default_signup_next_button_active.xml, app/src/main/res/drawable/button_default_signup_next_button_inactive.xml, app/src/main/res/drawable/ic_check_ok_sign.xml, app/src/main/res/drawable/ic_check_x_sign.xml, app/src/main/res/layout/activity_login.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_signup_email_set_email_address.xml, app/src/main/res/layout/fragment_signup_email_set_password.xml, app/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml, app/src/main/res/layout/fragment_signup_email_set_profile.xml, app/src/main/res/navigation/nav_graph_login.xml, app/src/main/res/values/colors.xml, app/src/main/res/values/strings.xml
- LoginActivity에 Navigation 적용
- LoginFragment 생성 및 LoginActivity 코드 LoginFragment으로 Migration
- nav_graph_login.xml 생성 및 작성
----
- 가입할 이메일 설정 Fragment 생성 및 레이아웃 적용
- 비밀번호 설정 및 확인 Fragment 생성 및 레이아웃 적용
- 자신의 프로필 설정 Fragment 생성 및 레이아웃 적용
resolved: #109
=> #109 [layout] Signup with Email

app/src/main/java/com/daily/dayo/di/NetworkModule.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt, app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt, app/src/main/java/com/daily/dayo/post/adapter/PostImageSliderAdapter.kt, app/src/main/java/com/daily/dayo/profile/FolderFragment.kt, app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt, app/src/main/java/com/daily/dayo/profile/MyProfileEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/OtherProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt
- 도메인 주소 만료로 인한 서버 주소 변경
----
- MyProfileFragment 서버 연동
- 현재 자신의 Profile 조회가 가능하도록 변경
- MyProfileEditFragment 서버 연동
- 현재 자신의 Profile이 수정 시 나타나도록 서버 연동
- Profile 닉네임 및 사진 변경 시, 적용 가능하도록 서버 연동
- 변경 후, 서버에 성공적으로 반영된 경우 MyProfileFragment으로 이동하도록 설정
- 변경 후, 서버에 성공적으로 반영된 경우 requestMyProfile() 요청을 다시 보내 변경된 Profile을 실시간으로 확인가능 하도록 설정
resolved: #110
=> #110 [feature] MyProfileFragment, MyProfileEditImageOptionFragment

app/src/main/java/com/daily/dayo/profile/MyProfileEditFragment.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt, app/src/main/java/com/daily/dayo/util/ButtonActivation.kt
- TextView에 대한 활성화/비활성화 처리하는 Util 작성
- MyProfileEditFragment 일부 Functions 목적에 맞게 분리및 생성
- 프로필 변경 Fragment에서, 4가지 경우에 대한 버그 수정및 구현
1. 프로필 사진과 닉네임 모두 변경하고자 하는 경우
2. 프로필 사진만 변경하고자 하는 경우
- 프로필 사진을 다른 사진으로 변경하고자 하는 경우
- 프로필 사진을 초기화하는 경우
3. 닉네임만 변경하고자 하는 경우
4. 모두 변경하지 않고자 하는 경우
resolved: #119
=> #119 [bug] Error occurs when only one thing is changed in MyProfileEditFragment

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt, app/src/main/java/com/daily/dayo/repository/HomeRepository.kt, app/src/main/java/com/daily/dayo/util/GridSpacingItemDecoration.kt, app/src/main/res/drawable/ic_like_default.xml, app/src/main/res/layout/fragment_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/item_main_post.xml
- HomePostItem Like 버튼 클릭 구현 및 서버 연동 구현
- Like 클릭 및 Like된 버튼 클릭시 Like 취소 구현
- 동일한 Post에 대해 Like를 했었는 지에 대한 판단 여부 **미구현 (현재 해당 값을 서버에서 받아오고 있지 않음)**
- Home 화면 여백 등의 디자인 변경으로 인한 레이아웃 수정
resolved: #124
=> #124 [feature] HomePostItem

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt, app/src/main/java/com/daily/dayo/repository/HomeRepository.kt, app/src/main/res/values/strings.xml
- HomeFragment에서 카테고리 선택 시, 카테고리에 맞는 Post List가 나오도록 서버 연동
resolved: #126
=> #126 [feature] HomeFragment Post List

app/src/main/java/com/daily/dayo/network/folder/FolderApiHelper.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/folder/FolderApiService.kt, app/src/main/java/com/daily/dayo/profile/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/profile/FolderFragment.kt, app/src/main/java/com/daily/dayo/profile/FolderOptionFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Folder.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/FolderEditViewModel.kt, app/src/main/java/com/daily/dayo/repository/FolderRepository.kt, app/src/main/res/layout/fragment_folder.xml, app/src/main/res/navigation/nav_graph.xml
+ 기존의 폴더를 편집하는 기능 구현
+ 마이페이지의 폴더 리스트에서 폴더 선택 후 옵션메뉴를 통해 편집
resolved : #112
=> #112 [feature] FolderEditFragment

app/src/main/java/com/daily/dayo/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/follow/FollowFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/follow/FollowingListFragment.kt, app/src/main/java/com/daily/dayo/follow/adapter/FollowListAdapter.kt, app/src/main/java/com/daily/dayo/follow/viewmodel/FollowViewModel.kt, app/src/main/java/com/daily/dayo/network/follow/FollowApiHelper.kt, app/src/main/java/com/daily/dayo/network/follow/FollowApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/follow/FollowApiService.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/OtherProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/model/Follow.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/OtherProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/FollowRepository.kt, app/src/main/res/drawable/edittext_background_follow_search.xml, app/src/main/res/layout/fragment_follower_list.xml, app/src/main/res/layout/fragment_following_list.xml, app/src/main/res/layout/item_follow.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
+ 타인의 프로필에서 팔로우하는 기능 구현
+ 팔로우 시 팔로우 수가 즉각적으로 업데이트 되도록 함
+ 팔로우 및 팔로잉 리스트 보여주기
+ 리스트 내에서 팔로우 및 팔로잉 취소 기능 구현
+ 팔로우 취소 시 Dialog를 띄우며 취소 시 팔로우 버튼이 그대로 유지 되고, 확인 시 언팔로우가 실행되도록 함
resolved: #114
=> #114 [feature] FollowFragment

app/src/main/java/com/daily/dayo/util/DefaultDialog.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteUploadImageListAdapter.kt, app/src/main/res/drawable/dialog_option_default_bottom.xml, app/src/main/res/drawable/dialog_option_default_top.xml, app/src/main/res/drawable/ic_img_delete_gray_5.xml, app/src/main/res/drawable/selector_button_write_post_upload.xml, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/fragment_write_image_option.xml, app/src/main/res/layout/item_write_post_upload_image.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
- Layout
- Default Dialog에서 Device의 가로, 세로 크기 구하는 function 생성
- Dialog 크기 조정 및 하단 여백 추가
- 사진 선택 시, 갤러리 선택과 사진 촬영 중 선택하는 옵션을 고르는 Fragment Layout
- SignupEmailSetProfileImageOptionFragment 수정
- WriteImageOptionFragmen 생성
- 디자인 변경에 따른 WriteFragment 여백 및 크기 등 전체적인 레이아웃 수정
- Feature
- 이미지 업로드시, 
- 갤러리 선택과 사진 촬영 중 선택할 수 있는 옵션 구현
- 갤러리 선택및 사진 촬영시 여러 번 업로드 가능하도록 구현
- 업로드한 이미지를 선택한 뒤 다시 삭제 가능 하도록 하는 기능 구현
- 업로드 이미지가 제한 개수 5개를 넘으면 5개 까지만 업로드 되며, 사진 삭제 이전까지는 사진 추가 버튼이 보이지 않도록 구현
- 카테고리, 내용, 사진 모두 작성되어야 글 업로드 버튼이 활성화 되도록 구현 및 상황에 맞는 에러 메시지를 Dialog가 아닌 Toast 메시지로 나오도록 구현
- 작성한 내용에 대한 글자 수 세기 기능 추가 및 글자 수 제한 기능 구현
resolved: #133
=> #133 [feature] WriteFragment

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/home/model/ResponseHomePost.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/res/layout/fragment_post.xml, app/src/main/res/layout/item_main_post.xml
- HomeFragment와 PostFragment에서 좋아요 클릭 여부 서버 연동하여 표시
- refreshFragment 추가
- HomeFragment에서 좋아요 버튼을 누른경우, PostFragment에서 좋아요 버튼을 누른 것이 반영되며, PostFragment에서 좋아요 버튼을 누른경우 HomeFragment로 돌아왔을 떄 좋아요 버튼을 누른 것이 반영되도록 구현
- 각 카테고리 별로 Post들을 분류하였을 때 좋아요 버튼을 누르더라도 카테고리가 그대로 유지되도록 구현
resolved: #145
=> #145 [feature] LikeButton in HomeFragment, PostFragment

.idea/.gitignore, app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt
- HomeFragment에서 카테고리 선택 후, PostFragment로 이동한 뒤, 다시 HomeFragment로 이동하면 카테고리 버튼은 그대로임에도 리스트는 전체 PostList가 나타나는 버그 해결
resolved: #147
=> #147 [bug] HomeFragment

app/src/main/java/com/daily/dayo/login/LoginRepository.kt, app/src/main/java/com/daily/dayo/login/LoginViewModel.kt, app/src/main/java/com/daily/dayo/login/model/LoginEmail.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelper.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiService.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailCompleteFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt, app/src/main/res/values/strings.xml
- 이메일 계정 회원가입 구현
resolved: #151
=> #151 [feature] LoginFragment with Email Signup

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/NewPostListFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/res/layout/fragment_new_post_list.xml
+ NewPostListFragment 구현
+ 기존의 Dayo Pick의 어댑터를 재사용하기위해 랭킹 유무를 구분하는 변수를 추가하여 New Post List에는 랭킹 이미지가 나타나지 않도록 함
+ 디자인 변경에 따라 아이템 추가 및 크기 조정
resolved: #141
=> #141 [feature] NewPostListFragment

app/src/main/java/com/daily/dayo/profile/MyProfileOptionFragment.kt, app/src/main/res/layout/fragment_my_profile.xml, app/src/main/res/layout/fragment_my_profile_option.xml, app/src/main/res/values/strings.xml
- 자신의 프로필 변경 Fragment에서 옵션 버튼을 누르는 경우 등장하는 Dialog 디자인 수정
resolved: #153
=> #153 [layout] MyProfileFragment Option Dialog

app/src/main/java/com/daily/dayo/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteFolderAdapter.kt, app/src/main/res/navigation/nav_graph.xml
+ 글 작성 시 폴더 선택 기능 구현
+ 폴더를 선택하지 않았을 경우 글 업로드가 되지 않으며 토스트 메시지 출력
resolved: #157
=> #157 [feature] Choose a folder when writing

app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/java/com/daily/dayo/post/adapter/PostCommentAdapter.kt, app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt, app/src/main/res/layout/fragment_post.xml, app/src/main/res/layout/item_post_comment.xml, app/src/main/res/values/strings.xml
- 댓글 간의 구분선 삭제 및 Reaction Count List와 Comment 간의 구분선 추가
- 자신의 댓글 삭제 클릭 영역 확장
- 댓글 관련 디자인 변경에 따른 레이아웃 일부 수정
- 자신의 댓글 삭제 시, 다시 한 번 묻는 Dialog 생성
resolved: #156
=> #156 [layout] PostFragment Comment Delete Dialog

app/src/main/res/values-night/themes.xml, app/src/main/res/values/themes.xml
+ 상태바 색상 흰색으로 변경
+ 상태바의 아이콘과 텍스트는 흰색과 대조되는 색상으로 설정
resolved: #166
=> #166 [layout] Set StatusBar Color

app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt, app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/MyProfileFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileLikePostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Profile.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt, app/src/main/res/layout/fragment_folder.xml, app/src/main/res/layout/fragment_profile_like_post_list.xml, app/src/main/res/layout/item_folder_post.xml, app/src/main/res/layout/item_profile_like_post.xml, app/src/main/res/navigation/nav_graph.xml
+ 마이페이지의 좋아요 리스트 구현
+ API 통신 구현
+ 좋아요한 게시글 썸네일 이미지 클릭 시 해당 PostFragment로 이동하도록 함
+ 좋아요 리스트 레이아웃 수정
+ (수정하면서 폴더 내 게시글 아이템 리스트의 레이아웃도 함께 수정했어요!)
resolved: #168
=> #168 [feature] ProfileLikePostListFragment

app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressCertificateFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt, app/src/main/res/layout/fragment_signup_email_set_email_address.xml, app/src/main/res/layout/fragment_signup_email_set_email_address_certificate.xml, app/src/main/res/navigation/nav_graph_login.xml, app/src/main/res/values/strings.xml
- 이메일 인증 뷰 레이아웃 구현 및 일부 디자인 수정에 따른 레이아웃 수정
resolved: #172
=> #172 [layout] Add EmailCertificateFragment in Signup with Email

app/src/main/java/com/daily/dayo/profile/MyProfileFragment.kt, app/src/main/res/layout/fragment_folder.xml, app/src/main/res/layout/fragment_my_profile.xml, app/src/main/res/layout/fragment_other_profile.xml, app/src/main/res/layout/fragment_profile_bookmark_post_list.xml, app/src/main/res/layout/fragment_profile_folder_list.xml, app/src/main/res/layout/fragment_profile_like_post_list.xml
+ 내 프로필 화면 전체가 스크롤 되도록 변경
+ 탭 전환 시 viewpager의 height를 조절해 wrap_content로 동작하게 함
+ 다른사람 프로필 화면 전체가 스크롤 되도록 변경
+ 폴더페이지 화면 전체가 스크롤 되도록 변경
resolved: #176
=> #176 [layout] MyProfileFragment Scroll

app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt, app/src/main/java/com/daily/dayo/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileBookmarkPostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Profile.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt
+  마이페이지의 북마크 리스트 구현
resolved: #171
=> #171 [feature] ProfileBookmarkListFragment

app/src/main/java/com/daily/dayo/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/feed/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/feed/model/Feed.kt, app/src/main/java/com/daily/dayo/feed/viewmodel/FeedViewModel.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelper.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/profile/ProfileApiService.kt, app/src/main/java/com/daily/dayo/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/profile/adapter/ProfileBookmarkPostListAdapter.kt, app/src/main/java/com/daily/dayo/profile/model/Profile.kt, app/src/main/java/com/daily/dayo/profile/viewmodel/MyProfileViewModel.kt, app/src/main/java/com/daily/dayo/repository/ProfileRepository.kt, app/src/main/res/layout/item_feed_post.xml
+ 피드 게시물 북마크 기능 구현
resolved: #181
=> #181 [feature] Bookmark Feed Post

app/src/main/java/com/daily/dayo/MainActivity.kt, app/src/main/java/com/daily/dayo/notification/NotificationFragment.kt, app/src/main/java/com/daily/dayo/notification/adapter/NotificationListAdapter.kt, app/src/main/java/com/daily/dayo/notification/model/Notification.kt, app/src/main/res/drawable/ic_unread.xml, app/src/main/res/layout/fragment_notification.xml, app/src/main/res/layout/item_notification.xml, app/src/main/res/navigation/nav_graph.xml
- 알림 뷰 아이템 2가지 중, 제목만 존재하는 경우, 제목과 내용이 모두 존재하는 경우에 대하여 제목만 존재하는 경우에 내용을 visibility=”gone”시켜 하나의 아이템을 활용 할 수 있도록 레이아웃 구성
- NotificationFragment 생성으로 메뉴에서 알림 뷰로 가는 버튼 활성화 이에 따라 ListAdapter등 구현
resolved: #184
=> #184 [layout] NotificationFragment

app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/home/NewPostListFragment.kt, app/src/main/java/com/daily/dayo/home/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelper.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/home/HomeApiService.kt, app/src/main/java/com/daily/dayo/repository/HomeRepository.kt
- Dayo Pick List 게시글들 불러오도록 API 추가 및 연동 수정
- Dayo Pick List와 New List를 구분하기 위하여 기존에 HomePostList로 불러오던 최신글 API에 대하여 이름 수정
resolved: #189
=> #189 [feature] HomeFragment DAYO PICK List

app/src/main/java/com/daily/dayo/login/LoginViewModel.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelper.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiService.kt, app/src/main/java/com/daily/dayo/repository/LoginRepository.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt
- 이메일 계정 중복확인 기능 API 연동을 통하여 구현
resolved: #199
=> #199 [feature] Checking Email Duplicate in Signup

app/src/main/java/com/daily/dayo/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/search/SearchFragment.kt, app/src/main/java/com/daily/dayo/search/SearchResultFragment.kt, app/src/main/res/layout/fragment_search_result.xml, app/src/main/res/navigation/nav_graph.xml
- SearchResultFragment 상단바 고정 스크롤 레이아웃 적용
- HomeFragment에서 검색버튼 클릭시 SearchFragment로 이동 적용
- SearchFragment에서 검색버튼 클릭시 SearchResultFragment로 이동 적용
resolved: #205
=> #205 [layout] SearchFragment, SearchResultFragment

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/MainActivity.kt, app/src/main/java/com/daily/dayo/SharedManager.kt, app/src/main/java/com/daily/dayo/util/FirebaseMessagingServiceUtil.kt, build.gradle
+ FCM을 위한 프로젝트 생성 
+ FirebaseMessagingServiceUtil 클래스 생성 
+ 추후 서버로 토큰 전송하기
+ FCM 테스트 
resolved: #208
=> #208 [feature] FirebaseMessagingService

app/src/main/java/com/daily/dayo/login/LoginViewModel.kt, app/src/main/java/com/daily/dayo/login/model/LoginEmail.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelper.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiService.kt, app/src/main/java/com/daily/dayo/repository/LoginRepository.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressCertificateFragment.kt, app/src/main/res/layout/fragment_signup_email_set_email_address_certificate.xml, app/src/main/res/values/strings.xml
- 이메일 인증 API 서버와 연동하여 구현
resolved: #211
=> #211 [feature] Certificate Email Address in Signup

app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/res/navigation/nav_graph.xml
- 글 상세보기에서 태그 리스트 중 태그 하나를 클릭하면 해당 태그의 내용으로 검색화면으로 넘어가는 기능 구현
resolved: #213
=> #213 [feature] PostFragment Tag Search

app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/MainActivity.kt, app/src/main/java/com/daily/dayo/SharedManager.kt, app/src/main/java/com/daily/dayo/login/LoginActivity.kt, app/src/main/java/com/daily/dayo/login/LoginFragment.kt, app/src/main/java/com/daily/dayo/login/LoginViewModel.kt, app/src/main/java/com/daily/dayo/login/model/Login.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelper.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/login/LoginApiService.kt, app/src/main/java/com/daily/dayo/repository/LoginRepository.kt, app/src/main/java/com/daily/dayo/util/FirebaseMessagingServiceUtil.kt
+ FCM사용을 위해 디바이스 토큰을 서버로 보내도록 함
+ 로그인 성공 확인 후 전송
+ 백그라운드에서도 알림이 정상적으로 작동하도록 수정
+ 백그라운드에서 알림 아이콘 보이도록 설정
+ 백그라운드에서 알림에 관한 정보를 data로 받아 표시하도록 함 
resolved : #226
=> #226 [feature] Device Token API

app/src/main/java/com/daily/dayo/SharedManager.kt, app/src/main/java/com/daily/dayo/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/login/LoginEmailFragment.kt, app/src/main/java/com/daily/dayo/network/search/SearchApiHelper.kt, app/src/main/java/com/daily/dayo/network/search/SearchApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/search/SearchApiService.kt, app/src/main/java/com/daily/dayo/repository/SearchRepository.kt, app/src/main/java/com/daily/dayo/search/SearchFragment.kt, app/src/main/java/com/daily/dayo/search/SearchResultFragment.kt, app/src/main/java/com/daily/dayo/search/adapter/SearchTagResultPostAdapter.kt, app/src/main/java/com/daily/dayo/search/model/SearchDto.kt, app/src/main/java/com/daily/dayo/search/viemodel/SearchViewModel.kt, app/src/main/res/drawable/ic_remove_edittext.xml, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_search_result.xml, app/src/main/res/layout/item_search_keyword_recent.xml, app/src/main/res/layout/item_search_result_post.xml, app/src/main/res/navigation/nav_graph.xml
- 이메일 계정 로그인 화면에 들어가자마자 로그인 실패 메시지가 나오는 현상 해결
resolved: #240
=> #240 [bug] Show LoginFailMessage only LoginFailed

app/src/main/java/com/daily/dayo/SharedManager.kt, app/src/main/java/com/daily/dayo/setting/SettingFragment.kt
+ 로그아웃 기능 구현
+ preference에 저장된 모든 내용을 클리어 후
+ 로그인 화면으로 다시 돌아가도록 구현
resolved : #243
=> #243 [feature] Logout

app/src/main/java/com/daily/dayo/common/DefaultDialog.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt, app/src/main/res/drawable/selector_dialog_confirm_default_button.xml, app/src/main/res/values/strings.xml
+ 문의하기 페이지에서 문의 메일 보내기 클릭 시, 클립보드에 메일 주소가 복사되도록 구현
resolved: #276
=> #276 [feature] Add Contact Mail

app/src/main/java/com/daily/dayo/common/TimeChangerUtil.kt, app/src/main/res/values/strings.xml
- 댓글 및 게시글의 작성후 현재까지의 시간을 보여주는 경우, month에 대한 미설정으로 인해 날짜 표시가 부자연스러웠던 점 수정
=> #280 [bug] Time Display Bug

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
+ 마이페이지에서 옵션이 실행되지 않는 문제 해결
resolved: #303
=> #303 [bug] Fix ProfileFragment Option Button

app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/NotificationViewModel.kt
+ 알림 확인 로직을 개별 알림을 클릭해야 읽음 상태로 변경되도록 수정합니다.
resolved: #302
=> #302 [feature] Change Notification Confirmation Logic

app/src/main/res/layout/fragment_folder.xml
- FolderFragment에서 Constraint가 적절하게 걸려있지 않아 이미지가 정상적으로 보이지 않는 문제 해결
- resolved: #301
=> #301 [bug] FolderFragment RecyclerView ConstraintMissing

app/build.gradle, app/src/main/java/com/daily/dayo/data/datasource/remote/firebase/FirebaseMessagingService.kt
+ 앱 실행 중 알림을 보내는 경우 앱이 종료되는 에러 발생해결
resolved: #306
=> #306 [bug] Fix Notification Error While App Is Running

app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionMineFragment.kt, app/src/main/res/layout/fragment_post.xml, app/src/main/res/layout/item_feed_post.xml, app/src/main/res/values/strings.xml
+ 게시글 상세페이지 레이아웃을 변경된 피드 레이아웃과 동일하게 적용
+ 좋아요, 댓글 숫자 변경
+ 태그 한줄로 나타나도록 변경
+ 댓글이 존재하지 않는 경우 안내문구 추가
resolved: #286
=> #286 [layout] Update Post Fragment Layout

app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt
- Placeholder로 LottieAnimationView 사용을 위한 수정 간 누락된 GlideLoadUtil에서의 import 구문들 추가
- resolved: #313
=> #313 [bug] Missing import statement

app/build.gradle
+ minSdkVersion 26으로 올리기
resolved: #315
=> #315 [refactoring] Change to minSdkVersion 26

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/FollowViewModel.kt, app/src/main/res/layout/fragment_follow.xml, app/src/main/res/layout/fragment_follower_list.xml, app/src/main/res/layout/fragment_following_list.xml
+ 팔로워, 팔로잉 탭 전환 시 레이아웃이 제대로 나타나지 않는 문제 수정 
resolved: #319
=> #319 [bug] Fix Follower, Following Empty View

app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/member/RequestUpdateMyProfileUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
+ 프로필 이미지 초기화 여부를 boolean값으로 보내도록 수정
resolved: #317
=> #317 [feature] Change update profile api

app/src/main/java/com/daily/dayo/common/dialog/DefaultDialog.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
- 글 작성시, 태그옵션 및 폴더에서 다시 글쓰기로 돌아갈 때 대용량 이미지를 업로드한 경우 딜레이가 생길때 로딩중임을 알려주는 Loading Dialog 표시
- resolved: #328
=> #328 [feature] Create Loading Dialog in WriteOptionFragment

app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_home_new_post_list.xml, app/src/main/res/layout/fragment_post.xml, app/src/main/res/layout/item_feed_post.xml
+ 홈 화면(dayo pick post, new post), 피드 당겨서 새로고침기능 추가
+ 피드, 게시글 화면 레이아웃 일부 수정
resolved: #324
=> #324 [layout] Change SwipeRefreshLayout in Home, Feed Fragment

app/src/main/java/com/daily/dayo/common/dialog/LoadingAlertDialog.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordConfirmationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionMineFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportPostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/report/ReportUserFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordNewFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/withdraw/WithdrawFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt
- 서버에 POST 요청을 보내는 등 사용자 작업후 작업이 완료될 때까지 사용자가 기다릴 수 있도록 Dialog를 표시
- resolved: #334
=> #334 [feature] Show LoadingDialog during POST Networking

app/src/main/res/anim/translate_from_left_in.xml, app/src/main/res/anim/translate_from_right_in.xml, app/src/main/res/anim/translate_nothing.xml, app/src/main/res/anim/translate_to_left_out.xml, app/src/main/res/anim/translate_to_right_out.xml, app/src/main/res/layout/fragment_folder_setting.xml, app/src/main/res/layout/fragment_folder_setting_add.xml, app/src/main/res/layout/fragment_post.xml, app/src/main/res/layout/fragment_profile_edit.xml, app/src/main/res/layout/fragment_write_option.xml, app/src/main/res/navigation/nav_graph.xml
- 쓸어넘기듯이 좌우로 이동하는 Navigate animation 레이아웃 파일 추가
- 이동할 때 우측에서 위로 쌓이는 Navigation 레이아웃 파일 추가
- 아무 동작도 하지 않는 Navigation 레이아웃 파일 추가
- PostFragment로 이동하는 경우, 우측에서 위로 쌓이는 Navigate animation 적용
- 설정창으로 이동하는 경우, 쓸어넘기듯이 좌우로 이동하는 Navigate animation 적용
- navigate하는 경우 새로운 페이지를 넘어가면서 이전 페이지가 새로운 페이지가 모두 로딩되기 전임에도 흰색으로 처리되는 문제를 아무 동작도 하지 않는 Navigate Animation을 이용하여 해결
- resolved: #337
=> #337 [feature] Add Animation when Navigate

app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
1. 게시글 수정 시 카테고리 안바뀌는 오류
a. viewmodel에 저장된 값을 이용하도록 변경
2.  폴더 이미지를 수정하는 경우 preview 변경되지 않는 오류
a. 이미지 수정 후 한번 더 기존 이미지 불러오지 않도록 변경
3. 게시글 삭제 시 홈 화면 리프레시
a. onResume상태마다 게시글을 다시 불러오도록 변경
resolved : #341
=> #341 [bug] Error when modifying, deleting post and folder

app/build.gradle, app/proguard-rules.pro, app/src/main/java/com/daily/dayo/data/di/NetworkModule.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
+ Proguard rules 설정 추가
+ import 에러 수정
+ network가 Debug 모드에서만 실행되던 코드 수정
resolved: #345
=> #345 [chore] Set proguard rules

app/build.gradle, app/src/main/java/com/daily/dayo/data/datasource/remote/block/BlockApiService.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/block/BlockRequest.kt, app/src/main/java/com/daily/dayo/data/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/data/repository/BlockRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/BlockRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/block/RequestBlockMemberUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/PostViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt, app/src/main/res/layout/dialog_defalt_explanation_confirm.xml, app/src/main/res/layout/fragment_post_option.xml, app/src/main/res/layout/fragment_profile_option.xml, app/src/main/res/values/strings.xml, build.gradle
+ 사용자 차단 옵션 추가 (게시글, 프로필)
resolved: #347
=> #347 [feature] Add User Blocking Options

app/src/main/java/com/daily/dayo/data/datasource/remote/block/BlockApiService.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/block/BlockRequest.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberResponse.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/retrofit/factory/NetworkResponseCall.kt, app/src/main/java/com/daily/dayo/data/mapper/ProfileMapper.kt, app/src/main/java/com/daily/dayo/data/repository/BlockRepositoryImpl.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/model/BlockUser.kt, app/src/main/java/com/daily/dayo/domain/repository/BlockRepository.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/block/RequestBlockListUseCase.kt, app/src/main/java/com/daily/dayo/domain/usecase/block/RequestUnblockMemberUseCase.kt, app/src/main/java/com/daily/dayo/presentation/adapter/BlockListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt, app/src/main/res/drawable/button_list_gray.xml, app/src/main/res/drawable/ic_block.xml, app/src/main/res/layout/fragment_setting.xml, app/src/main/res/layout/fragment_setting_block.xml, app/src/main/res/layout/item_block.xml, app/src/main/res/navigation/nav_graph.xml
+ 설정에 차단 관리 추가
+ 차단 해제 
성공적인 응답인데 body가 null로 오는 경우가 있어서 `NetworkResponseCall` 부분 수정했습니다.
resolved: #352
=> #352 [feature] Unblock User

app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt
+ 카카오 로그인 실패 시 로딩화면 무한으로 뜨는 것 해결
+ 기기에 카카오톡이 설치되어있는데 로그인이 되지 않는 경우, 웹으로 로그인을 할 수있도록 수정
+ 상세한 에러 로그 추가
resolved: #356
=> #356 [bug] fix kakao login

app/src/main/java/com/daily/dayo/common/dialog/LoadingAlertDialog.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/member/RequestCheckNicknameDuplicateUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
- 닉네임 설정간에 서버에 입력한 닉네임이 중복 닉네임인지 체크해 에러 출력 유무를 판단하는 기능 추가
- resolved: #362
=> #362 [feature] Check Nickname is duplicated at signupFragment

README.md
- ReadMe.md 파일에 다음과 같은 프로젝트 기본 정보를 추가했습니다.
- 프로젝트 소개 및 전체 팀원이 담긴 이미지 파일
- 사용한 언어 및 아키텍처
- 안드로이드 파트 팀원정보
- 저작권 정보
- ReadMe.md 파일에 다음과 같은 프로젝트 협업 진행 시 사용한 정보를 추가했습니다.
- Git convention
- Commit Convention
- XML Naming Convention
- Application SDK
- Release한 버전에 대한 Tag 등록 및 Release 등록
- 다음과 같은 정보들이 추가적으로 필요합니다.
- 기술 스택
- 팀원 소개글
- 저작권 및 사용정보 (License)
- #365
=> [doc] update Readme.md

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt, app/src/main/res/drawable/dialog_option_default_mid.xml, app/src/main/res/layout/fragment_folder_setting_edit_image_option.xml, app/src/main/res/layout/fragment_profile_edit_image_option.xml
- 선택 Dialog의 선택지가 3개인 경우 중간에 있는 옵션에 대한 Background xml파일 미존재로 해당 레이아웃 구현
- 이미지를 추가/선택하는 페이지에서 카메라 옵션이 누락된 경우에 대하여 카메라 옵션 추가
- 내 프로필 변경
- 폴더 추가및 편집
- resolved: #367
=> #367 [feature] Add camera options when adding pictures

app/src/main/java/com/daily/dayo/data/datasource/remote/alarm/AlarmApiService.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/alarm/AlarmPagingSource.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/alarm/AlarmResponse.kt, app/src/main/java/com/daily/dayo/data/repository/AlarmRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/AlarmRepository.kt, app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/NotificationViewModel.kt, app/src/main/res/layout/fragment_notification.xml
+ 알림 리스트를 페이징 어댑터로 변경
resolved: #370
=> #370 [feature] Alarm List to Paging Adapter

app/src/main/java/com/daily/dayo/common/TimeChangerUtil.kt
- 게시글 및 댓글 작성시간이 비정상적으로 표시되는 현상 수정
- 기존 로직에서 LocalDateTime을 활용하는 방식으로 변경
- Duration 및 Period를 활용해, 넓은 범위의 시간 단위를 우선적으로 확인해 0이 아닌 경우 해당 단위를 활용해 표시할 수 있도록 설정
- resolved: #373
=> #373 [bug] Fix time display error

app/src/main/AndroidManifest.xml
+ 앱을 세로모드로 설정
+ 로그인 액티비티, 메인 액티비티의 screenOrientation를 portrait로 설정
resolved : #376
=> #376 [feature] Set Screen Orientation to Portrait

app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt, app/src/main/res/layout/fragment_setting_block.xml, app/src/main/res/navigation/nav_graph.xml
+ 차단 관리 페이지의 뒤로가기 버튼 동작 추가
+ 화면 전환 시 애니메이션 추가
resolved: #390
=> #390 [bug] Back Button In SettingBlockFragment

app/src/main/java/com/daily/dayo/presentation/activity/MainActivity.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, app/src/main/res/layout/fragment_folder.xml, app/src/main/res/layout/fragment_follow.xml, app/src/main/res/layout/fragment_my_page.xml, app/src/main/res/layout/fragment_post.xml, app/src/main/res/menu/menu_main_bottom.xml, app/src/main/res/navigation/nav_graph.xml
+ 바텀 네비게이션으로 접근하는 마이페이지와 이외 방법으로 접근할 수 있는 프로필 페이지를 분리
resolved: #392
=> #392 [feature] Separate MyPageFragment and ProfileFragment

app/src/main/java/com/daily/dayo/presentation/fragment/setting/information/InformationFragment.kt, app/src/main/res/layout/fragment_information.xml
=> #394 [feature] Add App Version Name

app/src/main/java/com/daily/dayo/common/CustomDividerDecoration.kt, app/src/main/java/com/daily/dayo/common/TimeChangerUtil.kt, app/src/main/java/com/daily/dayo/domain/model/Notice.kt, app/src/main/java/com/daily/dayo/presentation/adapter/NoticeListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/notice/NoticeListFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/NoticeViewModel.kt, app/src/main/res/layout/fragment_notice_list.xml, app/src/main/res/layout/item_notice_post.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
- 공지사항 관련 레이아웃 구현
- 공지사항 리스트에 대한 아이템 레이아웃 구현
- 공지사항 리스트가 보여지는 페이지에 대해 Fragment를 활용한 구현
- YYYY.MM.DD 포맷으로 날짜를 표시할 수 있도록 TimeChangerUtil의 관련함수 `getFullStringTime`구현
- RecyclerView의 아이템 간 Divider를 표시할 수 있는 Custom Divider Decoration 구현
- resolved: #398
=> #398 [layout] Create notice list page layout

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt
+ MyPageFragment에서 옵션 버튼 클릭 시 잘못된 memberId를 전달하는 코드 수정
+ MyPageFragment와 ProfileFragment의 분리로 인해 불필요해진 조건 삭제 
resolved: #400
=> #400 [bug] Fix Profile MemberId Value

app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/res/drawable/background_white_radius_32.xml, app/src/main/res/drawable/ic_home_empty.xml, app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_home_new_post_list.xml, app/src/main/res/values/strings.xml
- 홈 화면에서 DAYO PICK과 NEW 각각의 탭에서 게시글이 존재하지 않는 경우 표시할 Empty view 구현
- Empty View에서 DAYO PICK탭에서 게시글이 존재하지 않을 경우, NEW 탭으로 이동할 버튼 표시 구현
- NEW탭에서 게시글이 존재하지 않을 경우, 글 작성으로 이통할 버튼 구현
- Radius가 32인 Background Drawable 파일 추가
- Empty VIew에서 표시할 이미지 파일 추가
- resolved: #404
=> #404 [layout] Create empty view at home

app/src/main/java/com/daily/dayo/data/datasource/remote/search/SearchResponse.kt, app/src/main/java/com/daily/dayo/data/repository/SearchRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/SearchRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/search/RequestSearchTotalCountUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/SearchViewModel.kt
+ 검색 API 수정에 따라 검색 결과 개수 요청
---
+ API응답으로 잘못된 값이 오고 있어 이 부분도 마저 확인 후 머지하겠습니다~! 
resolved: #375
=> #375 [bug] Modify Search Results Count

app/src/main/java/com/daily/dayo/data/mapper/FolderMapper.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt
+ folder 정보가 제대로 매핑되어있지 않는 부분 수정 
resolved : #422
=> #422 [bug] Not Visible Folder Option Button

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt
+ 기존의 프로필 수정페이지에 닉네임 중복 확인 기능 추가
resolved : #424
=> #424 [feature] Confirm Duplication Nickname

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/res/drawable/button_follow_green.xml, app/src/main/res/drawable/button_follow_white.xml, app/src/main/res/layout/fragment_profile.xml
+ 프로필의 팔로우, 팔로잉 버튼을 체크박스에서 버튼으로 수정
+ 팔로우, 팔로잉 응답이 정상적일 경우 프로필 업데이트 
+ 네트워크 응답이 정상적이지 않을 경우 네트워크 에러를 알리는 토스트 메시지를 띄워줌
resolved: #408
=> #408 [bug] change profile follow button logic

app/src/main/java/com/daily/dayo/data/mapper/ProfileMapper.kt, app/src/main/java/com/daily/dayo/domain/model/Profile.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt
+ API 기능 변경에 따른 수정 
+ MyPageFragment에서 내 프로필 정보를 요청하는 경우
+ ProfileFragment에서 다른 사람이 아닌 나의 프로필 정보를 요청하는 경우
+ 위의 두 가지 경우 내 프로필 정보임을 의미하는 요청을 하도록 변경
resolved : #432
=> #432 [feature] Change Profile Request Api in MyProfileFragment

app/build.gradle, app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt, app/src/main/java/com/daily/dayo/data/di/NetworkModule.kt, app/src/main/java/com/daily/dayo/presentation/fragment/policy/PolicyFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
+ 기존에 하드코딩되어있던 BaseUrl을 `BuildConfig.BASE_URL`를 통해 설정하도록 변경
+ `build.gradle` 설정으로 debug와 release의 url을 분리
+ `local.properties` 파일에서 BASE_URL_DEBUG, BASE_URL_RELEASE을 추가하여 실행하면 됩니다!
resolved: #431
=> #431 [chore] Set Base Url

app/src/main/java/com/daily/dayo/DayoApplication.kt
- 메모리가 부족해지는 경우 Glide가 사용하는 메모리에 대한 대처를 명시적으로 처리하는 부분 누락
- https://github.com/Daily-DAYO/DAYO_Android/issues/413#issuecomment-1639509103
=> [feature] Add Glide Memory Handling (missing part)

app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/FeedViewModel.kt, app/src/main/res/layout/item_feed_post.xml
- DataBinding을 활용해 리액션 버튼이 클릭되면, 게시글 전체 내용이 아닌 해당 부분만 변경될 수 있도록 구현
- 기존에 좋아요 수를 수동으로 추가해줬던 부분을 서버에서 받아온 응답값으로 반영할 수 있도록 로직 변경
- resolved: #448
=> [bug] Fix delayed reaction occurs when the reaction button is clicked

app/src/main/java/com/daily/dayo/data/di/CoroutinesDispatchersModule.kt
+ `CoroutinesDispatchersModule` 파일의 잘못된 import 삭제 
resolved: #452
=> #452 [bug] Remove Invalid Import in CoroutinesDispatchersModule

app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/res/navigation/nav_graph.xml
+ `nav_graph.xml`에서 `SearchResultFragment`의 argument제거
+ 피드, 게시글에서 태그 클릭 시 `searchViewModel`로 키워드 전달
+ `popUpTo` 설정으로 백스택을 제거해 뒤로가기 시 이전 검색창이 다시 표시되지 않도록 함 
+ 이전 검색창이 표시되지 않는 대신 홈에서 검색 시 뒤로가기를 눌렀을 때 최근 검색창이 뜨도록 함
resolved: #454
=> #454 [bug] Remove SearchResultFragment Argument

app/build.gradle, app/proguard-rules.pro
+ release 빌드 시 `minifyEnabled`  true 설정
+ `proguard-rules` 추가 설정
+ 네트워크 통신부와 일부 모델을 위해 규칙 추가
resolved: #464
=> #464 [chore] Set MinifyEnabled

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/presentation/activity/MainActivity.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/res/values/strings.xml
- `AndroidManifest.xml` 파일이 아닌 `build.gradle`이 잘못 병합된 부분에 대한 정정
=> [bug] Fix Fix incorrectly merged file

app/src/main/res/drawable/ic_lock.xml, app/src/main/res/layout/item_profile_folder.xml
- 마이페이지에서의 폴더 리스트 중 공개설정이 "비공개"로 설정되어있는 폴더는 폴더 이름 좌측에 자물쇠 표시가 있어야 하는 데 보이지 않는 현상 해결
- 공개설정이 비공개로 되어있는 경우에는 자물쇠 표시가 보여질 수 있도록 DataBinding을 활용해 구현
- resolved: #470
=> [bug] Fix private folder flag is not visible

app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/res/layout/fragment_post.xml
- 좋아요 버튼을 누른 사람이 없는 경우 (post.heartCount가 0인 경우) 좋아요 버튼 Click Listener에 대해 null 처리
- Databinding을 활용한 ClickListener 처리로 Fragment의 함수를 활용하기 위해 Data로 PostFragment를 넣어줌
- resolved #489
=> [feature] Disable viewing the likes list function when no one likes that post

app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileSettingViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/SettingNotificationViewModel.kt
- when 문 내부에서 else condition이 없는 등의 이유로 컴파일 에러가 생기는 부분 해결
- resolved: #491
=> [bug] Some codes are missing else condition in when statement

app/src/main/java/com/daily/dayo/common/TextUtil.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt, app/src/main/res/layout/fragment_folder_setting_add.xml, app/src/main/res/layout/fragment_write_folder_add.xml
+ 폴더 이름에 이모티콘을 넣을 수 있도록 변경
resolved: #477
=> #477 [feature] Change to include emoticons in folder titles

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/res/layout/fragment_folder_setting_add.xml
+ 폴더 Subheading의 글자수 제한 설정
resolved: #497
=> #497 [feature] Set folder subheading limit

app/build.gradle, app/src/main/java/com/daily/dayo/DayoApplication.kt, build.gradle, presentation/build.gradle
- Application 유저에 대한 데이터 수집을 위한 Firebase Crashlytics 및 Analytics 추가 작업
- presentation module 수준의 build.gradle의 plugin에서 gms를 삭제함에 따라 기존에 App 모듈과 중복으로 유지하던 google-services.json 파일 삭제처리
- gms 관련 버전 업데이트 처리
- 기존 presentation 모듈에 포함되어있었지만 커밋되지 않고 별도로 관리하던 `google-services.json` 개별 삭제필요
- resolved: #503
=> [feature] Add Firebase Crashlytics, Analytics

presentation/src/main/java/daily/dayo/presentation/adapter/FeedListAdapter.kt, presentation/src/main/java/daily/dayo/presentation/fragment/feed/FeedFragment.kt, presentation/src/main/res/layout/item_feed_post.xml, presentation/src/main/res/navigation/nav_graph.xml
+ 피드 게시글에서 좋아요 개수가 0보다 클 때 `postLikeUsersFragment`로 이동하는 기능 추가
resolved : #521
=> [bug] Navigate FeedFragment to PostLikeUsersFragment

presentation/src/main/java/daily/dayo/presentation/view/Button.kt, presentation/src/main/java/daily/dayo/presentation/view/FilledTextField.kt
+ 일부 custom component에 누락된 Modifier 파라미터를 추가 
#544
=> Add Modifier Parameter to Custom Component

presentation/src/main/java/daily/dayo/presentation/view/BottomSheetDialog.kt
- 일반적으로 표시될 기본 색상값과 강조될 색상값에 대해 개발자가 설정할 수 있는 parameter 추가
- icon Color와 check Color를 설정할 수 있는 2개의 parameter 추가 및 기본값을 각각 Gray1과 Primary Green으로 설정
- #550
=> #550 [feature] Add a parameter to modify the default and check colors in BottomSheetDialog

presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt, presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/home/HomeNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/post/PostNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/post/PostScreen.kt
+ Compose Navigation 기반 작업
+ 각 기능별로 NavGraph를 분리 
+ 탭에 해당하는 메뉴를 제외하고는 바텀바가 보이지 않도록 하기
+ 피드에서 게시글을 클릭했을 때 postId를 전달해서 특정 게시글의 경로로 이동할 수 있도록 예시 구현 
resolved #560
=> [feature] Compose Navigation

presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/post/PostLikeUsersScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/post/PostNavigation.kt, presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/PostViewModel.kt, presentation/src/main/res/drawable/ic_back_sign.xml
+ 게시글에서 좋아요 개수가 1이상일 때 숫자를 클릭하면 좋아요 리스트로 이동
+ 해당 리스트에서 팔로우 여부를 볼 수 있으며, 팔로우 및 취소 가능
+ 뒤로가기를 위해 navigator에 navigateUp 메서드 추가 및 적용
만들다보니까 미세하게 기본 background 색상이 다른 것 같아요. 
나중에 Figma의 변경된 color 적용하면서 theme 재정의를 해야할 것 같습니다!
resolved: #557
=> [layout] Post Like Users Screen

presentation/build.gradle, presentation/src/main/java/daily/dayo/presentation/activity/LoginActivity.kt, presentation/src/main/java/daily/dayo/presentation/common/dialog/DefaultDialog.kt, presentation/src/main/res/values/strings.xml
-  PlayStore의 버전과 비교해 업데이트가 가능한 경우, 더이상 앱이 진행되지 않고 강제로 업데이트를 진행할 수 있도록 추가
=> [feature] Add Application Force Update

presentation/src/main/java/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt
- 이메일 로그인시, 잘못된 아이디/비밀번호 입력으로 로그인 실패시 서버 연결 오류 메시지 노출 현상 해결
- 로그인 정보 오류로 인한 여부에 대한 변수 추가후 이에 대한 조건문 체크를 통해 오류메시지 노출
=> [bug] Fix wrong login fail message

presentation/src/main/java/daily/dayo/presentation/adapter/BlockListAdapter.kt, presentation/src/main/java/daily/dayo/presentation/adapter/FollowListAdapter.kt, presentation/src/main/java/daily/dayo/presentation/adapter/PostCommentAdapter.kt, presentation/src/main/java/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt, presentation/src/main/java/daily/dayo/presentation/common/GlideLoadUtil.kt, presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/post/PostFragment.kt
+ 이미지 화질 저하를 막기위해 뷰에 맞게 이미지 크기를 조정하도록 변경
+ 홈(DAYO PICK/ NEW)은 이미지 캐싱 및 preload를 위해 임의의 크기로 이미지를 저장해야 함
+ 이때, preload되지 않는 이미지와 화질 및 크기를 동일하게 보여주기 위해 동일한 값으로 설정
resolved: #576
=> [bug] FIx Image Quality Degradation

presentation/src/main/java/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt, presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/mypage/MyPageScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/post/PostLikeUsersScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/search/SearchPostHashtagScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt, presentation/src/main/java/daily/dayo/presentation/theme/Color.kt, presentation/src/main/java/daily/dayo/presentation/view/Button.kt, presentation/src/main/java/daily/dayo/presentation/view/CategoryHorizontalGroup.kt, presentation/src/main/java/daily/dayo/presentation/view/Chip.kt, presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt, presentation/src/main/java/daily/dayo/presentation/view/HomePostView.kt, presentation/src/main/java/daily/dayo/presentation/view/TextField.kt, presentation/src/main/java/daily/dayo/presentation/view/TopNavigation.kt, presentation/src/main/java/daily/dayo/presentation/view/dialog/BottomSheetDialog.kt, presentation/src/main/java/daily/dayo/presentation/view/dialog/CommentBottomSheetDialog.kt, presentation/src/main/java/daily/dayo/presentation/view/dialog/RadioButtonDialog.kt
- 디자인 변경사항에 따라 새로운 컬러 컴포넌트 적용
- 변경 사항에 따라 기존 컬러 수정
=> Refactoring color components

app/build.gradle, build.gradle, presentation/build.gradle
Dayo 1.1.4입니다요.
- targetSdkVersion을 34로 변경
=> Release v1.1.5

presentation/src/main/java/daily/dayo/presentation/screen/main/MainNavigator.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/mypage/MyPageScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/mypage/MypageNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/res/drawable/ic_next.xml, presentation/src/main/res/values/strings.xml
- 설정 화면 Compose로 만들기 
- 프로필 > 설정 버튼을 눌러서 이동
- 프로필 수정 버튼 누르면 프로필 수정 화면으로 이동
- 메뉴 리스트들은 공통 컴포넌트로 생성
- 정보 메뉴 옆에는 현재 앱의 versionName 표시
- resolved : #623
=> SettingsScreen

presentation/src/main/java/daily/dayo/presentation/screen/post/PostLikeUsersScreen.kt
- 좋아요한 사람의 리스트 중 본인 계정 옆에는 팔로우 버튼이 뜨지 않도록 처리 
- 게시글 좋아요 화면의 Preview를 볼 수 있도록 화면 분리 
- resolved : #664
=> Fix Incorrect follow buttons shown for current user in likes list

presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
- BottomSheetScaffold에 누락된 snackbarHost 추가
- resolved : #680
=> Add SnackbarHost to BottomSheetScaffold
