app/src/main/res/layout/fragment_post.xml
**버그 세부사항**
- 댓글 작성 시, 계속해서 줄바꿈을 하는 경우 Margin 등의 디자인이 깨지는 문제
- 댓글 작성 시, 우측 게시 버튼과 살짝 겹치는 문제
**추가 세부 사항 및 조치**
- Comment Layout 하단 padding 적용
- Comment 작성 하는 EditText에 maxLines 적용하여 3줄이상 작성 시 더 이상 공간을 증가시키지 않고 EditText내 스크롤로 동작하도록 설정
- 댓글 업로드 버튼 우측상단 고정에서 우측하단 고정으로 변경
resolved: #24
=> #24 [bug] PostFragment Comment

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteUploadImageListAdapter.kt, app/src/main/res/layout/fragment_write.xml, app/src/main/res/layout/item_write_post_upload_image.xml
- Manifest.xml에 이미지 파일 불러오기를 위한 저장소 권한 요청 추가
- 이미지 불러오기 및 파일 저장소 권한 요청 기능 추가
- 불러온 이미지를 보여주는데 Glide 활용에 따른 Build.gradle 수정
- 불러온 이미지를 Recyclerview에 보여줌에 따라, Recyclerview 위치 수정 및 불러온 이미지가 존재하는 경우, 기존에 이미지 추가 안내 Layout Invisible처리
- 불러온 이미지 CenterCrop 처리하여 정사각형으로 보여지도록 설정
- 불러온 이미지 각 모서리 Radius 처리
resolved: #59
=> #59 [feature] Image Upload in WriteFragment

app/src/main/java/com/daily/dayo/util/DefaultDialog.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/res/layout/dialog_default_confirm.xml, app/src/main/res/values/strings.xml
**Layout 변경 사항**
- 확인/취소 Dialog를 앱 전체적으로 사용하기 위하여 DefaultDialogConfirm Object 생성
- 글 작성 Fragment에서 Default Dialog Confirm를 사용하여 로딩 Dialog로 활용
resolved: #82
=> #82 [layout] DefaultDialogConfirm

app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetEmailAddressFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordConfirmationFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetPasswordFragment.kt, app/src/main/java/com/daily/dayo/signup/email/SignupEmailSetProfileFragment.kt, app/src/main/res/layout/fragment_signup_email_set_email_address.xml, app/src/main/res/layout/fragment_signup_email_set_password.xml, app/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml, app/src/main/res/layout/fragment_signup_email_set_profile.xml
- 이메일 계정으로 가입할 때의 화면 Fragment 디자인에 맞추어 개선
- 이메일 계정 정보 입력 Fragment들 Function들이 통일성이 있도록 변경
- 일부 Function 목적에 맞게 분리 및 생성
- 패스워드 설정 시 Count 누락 수정
- Next 버튼이 처음 화면에서 Enable="true"로 되어있던 Bug Fix
resolved: #120
=> #120 [layout] Improving Signup with Email

app/src/main/java/com/daily/dayo/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/feed/adapter/FeedCommentAdapter.kt, app/src/main/java/com/daily/dayo/feed/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/feed/model/Feed.kt, app/src/main/java/com/daily/dayo/feed/viewmodel/FeedViewModel.kt, app/src/main/java/com/daily/dayo/network/feed/FeedApiHelper.kt, app/src/main/java/com/daily/dayo/network/feed/FeedApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/feed/FeedApiService.kt, app/src/main/java/com/daily/dayo/repository/FeedRepository.kt, app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/item_feed_post.xml, app/src/main/res/layout/item_feed_post_comment.xml, app/src/main/res/navigation/nav_graph.xml
+ FeedFragment 레이아웃 디자인 변경사항 적용
+ 피드 관련 API통신 구현
+ databinding사용하여 게시글 정보 표시
+ 댓글이 없을 시 해당 레이아웃을 보이지 않도록 함
+ 댓글이 2개 초과일 경우 2개만 보이도록 하며, 더보기 문구를 띄움
+ 해시태그가 없을 시 해당 레이아웃을 보이지 않도록 함
+ 피드에서 작성자 프로필 클릭 시 해당 프로필로 이동
+ 댓글 더보기나 게시글 내용 클릭 시 해당 게시글의 PostFragment로 이동
+ 하트 아이콘 클릭 시 좋아요, 좋아요 취소 구현
resolved: #160
=> #160 [feature] FeedFragment

app/src/main/java/com/daily/dayo/network/post/PostApiHelper.kt, app/src/main/java/com/daily/dayo/network/post/PostApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/post/PostApiService.kt, app/src/main/java/com/daily/dayo/post/PostFragment.kt, app/src/main/java/com/daily/dayo/post/model/ResponsePost.kt, app/src/main/java/com/daily/dayo/post/viewmodel/PostViewModel.kt, app/src/main/java/com/daily/dayo/repository/PostRepository.kt, app/src/main/res/layout/fragment_post.xml
- 게시글 상세보기 북마크 기능 서버와 연동하여 구현
- 이미 북마크한 글인 경우 글 상세보기에서 글 북마크한 상태로 표시
- 글 상세보기 Fragment에서 서버에서 정보를 받아올 때, Bookmark 기존 여부 정보를 추가적으로 받아오도록 모델 수정
resolved: #178
=> #178 [feature] Post Bookmarking

app/src/main/java/com/daily/dayo/network/write/WriteApiHelper.kt, app/src/main/java/com/daily/dayo/network/write/WriteApiHelperImpl.kt, app/src/main/java/com/daily/dayo/network/write/WriteApiService.kt, app/src/main/java/com/daily/dayo/post/model/ResponsePost.kt, app/src/main/java/com/daily/dayo/repository/WriteRepository.kt, app/src/main/java/com/daily/dayo/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/write/adapter/WriteUploadImageListAdapter.kt, app/src/main/java/com/daily/dayo/write/model/Write.kt, app/src/main/java/com/daily/dayo/write/viewmodel/WriteOptionViewModel.kt, app/src/main/res/layout/fragment_write_option.xml, app/src/main/res/navigation/nav_graph.xml
- 글 상세보기에서 게시글 수정 클릭 시 글 작성화면으로 기존 글 콘텐츠가 삽입되면서 이동 구현
- 글 수정시, 이미지 삭제및 추가 불가능 처리
- 기존 글 수정 및 새로운 글 작성 구분을 위한 nav_graph.xml에서 WriteOptionFragment의 argument 추가
- 글 상세보기 기존 response Model 수정
- 글 작성에 대한 기존 글 수정 Model 추가
- privacy 설정 삭제
resolved: #162
=> #162 [feature] WriteModifyFragment

app/src/main/java/com/daily/dayo/SharedManager.kt
- 최근 검색어가 존재하지 않는 지 확인하는 조건문 오류 수정을 통하여  최근 검색한 태그 키워드들이 앱을 종료했다 다시 실행하는 경우 보이지 않는 현상 해결
resolved: #246
=> #246 [bug] Not Showing Recent SearchKeyword

app/src/main/java/com/daily/dayo/SharedManager.kt, app/src/main/java/com/daily/dayo/home/DayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/home/NewPostListFragment.kt, app/src/main/java/com/daily/dayo/home/adapter/HomeDayoPickAdapter.kt, app/src/main/res/layout/fragment_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_new_post_list.xml, app/src/main/res/layout/item_main_post.xml
- 홈 화면의 Item의 크기를 기기의 디스플레이 크기에 따라 늘어날 수 있도록 비율로 조정
- 홈 화면 Item간 여백 조정
- 홈 화면 Post들의 Thumbnail 이미지 로딩 최적화
- 홈 화면의 Item을 담는 Recyclerview의 width 크기를 Guideline에 따라 비율로 조정될 수 있도록 변경
- 홈 화면의 Item의 Margin을 XML을 구현하도록 설정하였으며, Decoration 설정 제거
- Coroutine을 활용해 Background에서 이미지를 로딩하도록 한 뒤, 작업이 끝나면 해당 이미지가 이미지뷰에 로딩되도록 설정
- Glide의 override를 통하여 ImageView의 크기에 맞게 받아오도록 하여, Memory 사용량 낮춤
- 이외의 관련 파일 Code Formatting
resolved : #248
=> #248 [bug] HomeFragment Item Margin, Loading

app/build.gradle, app/src/main/java/com/daily/dayo/common/GlideModule.kt, app/src/main/java/com/daily/dayo/domain/model/Post.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeFragmentPagerStateAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_home_new_post_list.xml, app/src/main/res/layout/item_main_post.xml, app/src/main/res/layout/item_main_post_shimmer.xml, app/src/main/res/values/colors.xml
- Glide 오류에 대한 디버깅 및 GlideModule 도입
- HomePagerStateAdapter에서 발생한 오류 디버깅
- HomeFragment에 대한 DAYOPICK 과 NEW에서 공통으로 사용하던 부분 제거 및 생성
- HomeFragment에서의 이미지 로딩 최적화
- HomeFragment에서의 이미지 로딩 완료 이전 스켈레톤 UI 구현
- GlideApp 사용을 위한 Compiler 추가
- Shimmer 사용을 위한 라이브러리 추가
- Alpha 0.3을 적용한 Gray3 추가
- You cannot start a load for a destroyed activity 오류 메시지에 대한 디버깅
- 이를 위해 GlideModule 파일 생성 및 Glide 사용시 활용
- adapter에서 Glide 사용 시, Constructor에 requestManager를 받아 이를 이용해 이미지 로드
- Layout 일부 자잘한 수정
- 관련 기능 구현 코드 Refactoring
- Swipe을 통한 Tab간 이동 기능 Disable
- 최초 HomeFragment create되는 경우에만 homeViewModel을 통해 PostList를 받아오도록 수정 및 Create되는 경우에는 무조건 전체 카테고리를 보도록 수정
- PagerStateAdapter에 대한 refreshFragment 관련 코드에서 notify 관련 함수 오류 경고 메시지에 따른 디버깅
- Layout에 ShimmerFrameLayout 추가하여 이미지 로딩 시 화면 구현
- 관련 …
=> #259 [feature] HomeFragment Image Loading Optimization

app/src/main/java/com/daily/dayo/data/datasource/remote/alarm/AlarmApiService.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/alarm/AlarmResponse.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/firebase/FirebaseMessagingService.kt, app/src/main/java/com/daily/dayo/data/di/ServiceModule.kt, app/src/main/java/com/daily/dayo/data/mapper/AlarmMapper.kt, app/src/main/java/com/daily/dayo/data/repository/AlarmRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/model/Notification.kt, app/src/main/java/com/daily/dayo/domain/model/Topic.kt, app/src/main/java/com/daily/dayo/domain/repository/AlarmRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/notification/RequestAllAlarmListUseCase.kt, app/src/main/java/com/daily/dayo/domain/usecase/notification/RequestIsCheckAlarmUseCase.kt, app/src/main/java/com/daily/dayo/presentation/activity/MainActivity.kt, app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/NotificationViewModel.kt, app/src/main/res/layout/item_notification.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
+ 알림 종류에 따라 아이템 출력
+ 읽음 여부 확인
+ Notification Fragment로 이동 시 읽지 않은 메시지는 모두 읽음 처리함
+ 예외 상황을 대비하여 읽지 않은 알림 아이템을 클릭하는 경우 읽음 처리함
+ 텍스트 중 닉네임 클릭 시 프로필로 이동
+ 알림 아이템 클릭 시 관련 게시글 혹은 프로필로 이동
+ MainActivity로 이동 후 알림 메세지에 담겨있는 데이터에 따라 동작
+ 팔로우 데이터인 경우 팔로우한 유저의 프로필로 이동 
+ 좋아요, 댓글 데이터인 경우 알림에 해당하는 게시글 페이지로 이동
+ 예외 상황으로 데이터가 없는 경우 알림 페이지로 이동
+ 현재 foreground에서의 동작 처리는 완료했지만, background 데이터 처리는 back-end측과 협의 필요
=> #255 [feature] Notification Fragment

app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FollowListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostCommentAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/WriteUploadImageListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt
- 기존 Glide를 사용시마다 URL 주소 및 기타 옵션에 대하여 설정하여 이미지뷰에 대한 일괄적인 업데이트가 불편했던 점을 개선하기 위해 공통 유틸 생성
- `GlideApp을` 사용하던 부분을 `RequestManager`로 대체
- Glide에 대한 옵션 값을 하나하나 설정해야 했던 부분들 교체
- Glide 사용시 `이미지뷰에 적용하는 Thread`와 `이미지를 로딩하는 Thread`를 분리
- override시 각 이미지뷰 크기에 맞게 Override 되도록 설정
- Util 사용이 불필요해보이는 경우 `RequestManager만` 사용하도록 함
- 일괄적 교체로 인한 누락 및 오류 존재 가능성 존재
- #270
=> #270 [feature] Create Glide Loading Util

app/src/main/java/com/daily/dayo/common/ListLiveData.kt, app/src/main/java/com/daily/dayo/common/ReplaceUnicode.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/post/PostResponse.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt
+ 기존태그 입력시 태그 중간에 빈칸 입력이 가능했던 현상 수정
+ 중복된 태그 추가 불가 설정
+ 태그가 수정된 경우에만 태그 페이지에서 확인 버튼이 활성화 되도록 설정
- 태그 입력후 확인 버튼을 눌러 글 작성화면으로 돌아갈 때 일시적으로 태그의 갯수가 2배가 되는 현상 수정
- 태그 4개 이상 입력시 8개 제한 에러 메시지가 나오면서 태그 저장이 정상적으로 되지 않는 현상 수정
- 기존 글 수정 저장 및 완료후, 수정한 게시글로 이동할 때 수정한 내용이 즉시 반영되지 않는 것으로 보이는 현상 수정
- 이미지 업로드 시, 5개 이하의 이미지를 선택했을 때 이미지 카운팅 에러로 인해 정상적으로 이미지가 올라가지 않는 현상 수정
- 기존에 글 업로드시, 내용을 작성하지 않은 채로 글 작성을 막았던 조건 제거
- 태그 추가시, 입력된 String에 존재하는 모든 공백 제거후 추가되도록 설정
- 태그 추가시, 빈 태그와 중복태그는 추가되지 않고 태그 입력칸만 비워지도록 설정
- 기존 태그가 0개인 경우에만 비활성화되던 확인 버튼을 0개인 경우에도 활성화되며, 태그 리스트가 그전에 입력했던 태그 리스트와 동일하지 않은 경우에만 확인 버튼이 활성화되도록 설정
- 태그 입력 완료후 저장하는 경우, 기존에 ViewModel에 저장되어있던 ListLiveData가 아닌 새로운 ListLiveData를 만들어 추가하여 저장하도록 설정
- 태그 입력 페이지에서 소프트 키보드 영역이 아닌 다른 영역을 클릭하면 키보드가 내려갈 수 있도록 설정
- 기존 글 수정시 응답 DTO가 잘못 설정되어있던 부분 수정
- 이미지 업로드시, …
=> #290 [bug] Fix Adding Tag Error, Edit Post Error, Image Upload Count Error, Remove the Do not post empty settings

app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/res/layout/fragment_home_dayo_pick_post_list.xml, app/src/main/res/layout/fragment_home_new_post_list.xml
- 홈 탭에서 하트를 누르는 경우 튕기는 버그 수정
- 로딩되는 경우에도 카테고리를 변경할 수 있도록 설정
- 초기 카테고리 initialize 오류로 인해 발생하는 버그 수정
- CoroutineScope(Dispatchers.Main) 대신 viewLifecycleOwner.lifecycleScope 사용
- 카테고리 오류 currentCategory.isInitialized을 사용하여 체크
- Shimmer가 카테고리 아래로 오게 설정 및 visibility 수정
- resolved: #278
=> #278 [bug] Update Like Error

app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/member/RequestCheckEmailAuthUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailCertificateFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
1. 비밀번호 찾기시 이메일 체크하는 과정에서 인증번호 받기를 누르지 않았는데도 인증번호 메일이 발송되는 현상
2. 이메일 체크 실패 후, 다시 올바른 이메일을 입력한 뒤 화면을 누르면 누른 수 만큼 다시 체크되어 실패메시지와 성공 메시지가 계속해서 교차해서 나타나는 현상
- 백엔드와 협의하여 이메일 존재여부 확인 및 인증메일 보내기가 결합되어 있던 API를 분리 요청함에 따라, 인증코드 요청 API를 추가로 생성하여 해결
- resolved: #295
=> #295 [bug] FindAccountPasswordCheckEmail Fragment Help Message

app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/policy/PolicyFragment.kt, app/src/main/res/drawable/ic_dayo_loading.xml, app/src/main/res/layout/fragment_login.xml, app/src/main/res/layout/fragment_policy.xml, app/src/main/res/navigation/nav_graph_login.xml, app/src/main/res/values/strings.xml
- 이용약관 및 개인정보처리방침 페이지를 표시할 Fragment 생성 및 Layout 설정
- LoginFragment 하단 안내메시지를 클릭하면 각각 이용약관 및 개인정보처리방침이 있는 웹으로 이동하여 보여질수 있도록 웹뷰로 보여줌
- 이용약관 및 개인정보 처리방침 클릭 여부에 따라 하나의 Fragment를 이용해 각각 다른 페이지가 보여질 수 있도록 설정
- resolved: #333
=> #333 [feature] Create PolicyFragment

.gitignore, app/build.gradle, app/proguard-rules.pro, app/src/main/AndroidManifest.xml, app/src/main/resources/sentry.properties, build.gradle, sentry.properties
- 로깅을 위한 Sentry 도입
- 추후 Proguard 적용에 대비하여 Progurad rule에 Sentry 관련 라이브러리가 제외되도록 설정
- `sentry.properties`는 각 개인 계정의 Auth Token이 담겨있으므로, 최초 Push후 수정되지 않도록 `.gitignore`에 추가
- 개발을 진행하는 경우 2개의 `sentry.properties` 파일에 자신의 AuthToken을 입력해야 정상적으로 빌드가 진행됩니다. Sentry 가입 및 팀 Join이후 아래의 링크에서 자신의 Token을 생성한 뒤 붙여넣으면 됩니다.
- https://sentry.io/settings/account/api/auth-tokens/
=> #339 [feature] Add Sentry Logging

app/src/main/res/layout/fragment_feed.xml, app/src/main/res/layout/fragment_find_account_password_check_email.xml, app/src/main/res/layout/fragment_find_account_password_check_email_certificate.xml, app/src/main/res/layout/fragment_find_account_password_complete.xml, app/src/main/res/layout/fragment_find_account_password_new_password.xml, app/src/main/res/layout/fragment_find_account_password_new_password_confirmation.xml, app/src/main/res/layout/fragment_folder_setting.xml, app/src/main/res/layout/fragment_login_email.xml, app/src/main/res/layout/fragment_report_post.xml, app/src/main/res/layout/fragment_report_user.xml, app/src/main/res/layout/fragment_setting_change_password_current.xml, app/src/main/res/layout/fragment_setting_change_password_new.xml, app/src/main/res/layout/fragment_signup_email_set_email_address.xml, app/src/main/res/layout/fragment_signup_email_set_email_address_certificate.xml, app/src/main/res/layout/fragment_signup_email_set_password.xml, app/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml, app/src/main/res/layout/fragment_signup_email_set_profile.xml, app/src/main/res/layout/fragment_withdraw.xml, app/src/main/res/layout/item_search_keyword_recommend.xml, app/src/main/res/layout/item_write_post_tag.xml
+  버튼의 그림자를 제거하기위해 모든 버튼에 `android:stateListAnimator="@null"` 추가
resolved: #343
=> #343 [layout] Set button animation to null

app/src/main/res/layout/fragment_post.xml
- 게시글 상세보기 페이지에서 댓글 작성시 여러줄이 생기는 경우에 `EditText` 칸이 영역을 넘어가는 버그 수정
- 영역 구분하는 divider view에 대해 Vertical bias 설정으로 영역에 맞춰서 올라갈수 있도록 구현
- 기존 marginTop과 Bottom을 ImageView기준으로 설정하던것에서 EditText 기준으로 변경
- resolved: #357
=> #357 [bug] post's comment box is out of bounds

app/src/main/java/com/daily/dayo/data/datasource/remote/member/MemberApiService.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/member/RequestSignUpEmailUseCase.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt
- 이메일 회원가입 과정 페이지에서, 프로필 설정간에 튕기는 원인
- LoadingDialog가 선언되지 않은채로 View Destroy및 다음으로 버튼 클릭시 사용하는 상황에 발생
- 프로필 이미지를 설정하지 않은 채로 넘어가는 경우에 발생
- LoadingDialog를 View를 Create하는 경우에 init하도록 설정 및 Dialog 사이즈 변경 코드 추가
- 프로필 이미지를 설정하지 않고 넘어가는 경우에 null로 서버에 보내도록 구현
- resolved: #359
=> #359 [bug] Fix Crash issue at signupEmailSetProfileFragment

app/src/main/java/com/daily/dayo/common/extension/NavControllerExtension.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/SettingFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/information/InformationFragment.kt, app/src/main/res/layout/fragment_information.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
- 정보 페이지 레이아웃 구현
- 기존 구현된 이용약관 및 개인정보 보호방침 페이지로 이동될 수 있도록 `navigation graph`에 해당 Fragment 추가 및 연결
- 앱 버전 관련 페이지에 대한 디자인 미구현 상태로 인한 해당 버튼 관련 동작 미구현 처리
- resolved: #379
=> #379 [layout] Create Information Layout

app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt
- 홈 화면에서 새로고침을 할때마다 외부적으로 아이템 변경이 일어나지 않았음에도 불구하고 Fade 애니메이션이 보여는 현상 해결
- 기존 `areContentsTheSame`를 통해 아이템을 비교해 Reclerview에서 보여지는 리스트의 아이템을 업데이트 하였으나, 아이템이 preload된 이미지가 새로고침할때마다 변경되어 아이템이 변경된것으로 인식된 것으로 확인
- 이에따라 contents 비교시 preload 이미지는 제외하고 아이템 변경을 인식하도록 구현
- resolved: #386
- [ListAdapter blink on refresh - StackOverFlow](https://stackoverflow.com/questions/71178205/listadapter-blink-on-refresh)
=> [bug] Fix fade animation is appeared when refreshing posts

app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt
- Glide를 사용해 이미지 캐싱시, 이미지 크기가 모든 이미지 리스트 페이지마다 일정하고, 큰 이미지의 경우엔 게시글만 존재함에 따라 디코딩된 이미지만 캐싱하도록 정책 설정
- 기존에 RequestOption이 정상적으로 작동되지 않던 코드 수정
- 리사이징 크기를 상수로 설정해 일괄적으로 설정할 수 있도록 구현
- resolved: #396
=> #396 [feature] Change Image options

app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt
- API 요청에 대한 400번대의 응답코드 값을 모두 API ERROR로 처리함에 따라 발생한 문제
- 자동 로그인 실행시 Token Refresh 과정에서 로그인이 되어있지 않은 경우 해당 값이 비어있으며 이에 따라 401 응답코드를 받음
- 따라서 API ERROR로 처리됨에 따라 서버 연결 토스트 메시지가 나오게 되는 현상 발생
- 이에 대해 401 응답코드로 오는 경우엔 API ERROR로 처리되지 않도록 분기처리
- resolved: #401
=> #401 [bug] Fix Network error toast message is always displayed when not logged in app

app/src/main/java/com/daily/dayo/common/ReplaceUnicode.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailCertificateFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCheckEmailFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordConfirmationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signin/LoginEmailFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetEmailAddressFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetPasswordConfirmationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetPasswordFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordCurrentFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordNewFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
- 공백제거를 위해 일반적인 띄어쓰기이외의 띄어쓰기와 동일한 형태를 보여주는 다른 유니코드들을 모두 한번에 제거할 수 있도록 별도의 함수 구현
- 글 상세보기에서 댓글을 다는 경우, 공백 제거 검사 이후 실제로 서버에 전송하는 경우 공백 제거 검사및 처리된 텍스트가 아닌 사용자가 입력한 텍스트가 서버에 전송되는 현상 수정
- 기존 기본적으로 제공되는 `trim()`을 사용한 경우 특수 공백문자까지 제거하는 `trimBlankText()`로 변경
- #190
=> [bug] Change Trim bugs

app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FolderSettingAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt
- Item을 비교하는 `DiffUtil` 작성 과정간 `areItemsTheSame` 및 `areContentsTheSame` 로직이 잘못 작성되어 있어 불필요한 새로고침과 애니메이션이 나타나는 현상 수정
- 내용이 아닌 주소값을 비교하는 `===` 로 비교하는 부분에 대해 수정
- `areItemsTheSame` 은 가능한 해당 아이템의 고유 ID로, `areContentsTheSame`는 해당 아이템의 미리보기 등 속도를 위한 요소를 제외한 요소들에 대한 비교로 처리할 수 있도록 수정
- resolved: #410
=> #410 [refactoring] Change diffUtil Logic

app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/PostViewModel.kt
- PostFragment에서 이전에 사용했던 PostFragment 내용이 보이는 문제에 대한 해결
- PostFragment가 Destroy되는 경우 해당 PostFragment에서 보여줬던 내용을 초기화한 이후에 Destroy되도록 구현
- 새로운 이미지를 보여주는 경우에 불필요한 Fade animation이 보여지지 않도록 `setPageTransformer`에 대해 빈 코드로 오버라이드
- resolved: #412
=> #412 Add Clean up Post Detail logic when postFragment is destroyed

app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt, app/src/main/res/layout/fragment_write_tag.xml, app/src/main/res/values/strings.xml
- 업로드 게시글의 태그 리스트 값 조작위치를 `Fragment`에서 `ViewModel`로 이동
- 기존에 `LoadingDialog`를 hide하는 시기를 `onDestroyView`가 호출되던 시점에서 `onStop`이 호출되던 시점으로 변경
- `writeViewModel`의 `postTagList`를 Observe해 `Chip ItemView`가 추가및 삭제되도록 로직 변경
- `DataBinding`을 활용해 `XML` 상에서 확인 버튼 및 현재 입력된 태그 개수등을 조작할 수 있도록 설정
- 입력 가능한 태그 글자수 15자로 설정
- #414
- #417
=> #414 Change tag limit, counting logic

app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
- Chip 내용에 따라 높이가 바뀌는 wrap_content로 height가 설정되어 요소들의 높이가 일정하지 않았던 문제를 48dp로 설정해 태그의 높이 설정
- #415
=> #415 Fix different height of tag elements

app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt
- `LoadingDialog`가 폴더 설정에서 나온 뒤 글 작성 페이지로 넘어간 뒤에 사라짐에 따라 어색한 부분에 대해 수정
- `onDestroyView`가 호출되던 시점에 Dialog를 dismiss하던 것에서 `onStop`이 호출되는 시점에 Dialog를 dismiss하는 것으로 변경 
- resolved: #417
=> #417 change when dialog disappears when leaving the folder fragment

app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt
- 글자 및 개수 제한 토스트 메시지가 지속적으로 불필요하게 표시되는 현상 개선
- WriteFragment에서 개수 제한을 체크하지 않고, ImageOption에서만 사진 개수를 제한 체크하도록 로직 변경
- 태그 리스트가 replace되는 로직을 제거해 불필요한 list 값 변경으로 토스트 메시지가 나타나는 현상 개선
- resolved: #416
=> #416 Change displaying limit toast message logic

app/src/main/java/com/daily/dayo/data/datasource/local/SharedManager.kt, app/src/main/java/com/daily/dayo/data/datasource/remote/firebase/FirebaseMessagingService.kt, app/src/main/java/com/daily/dayo/data/repository/MemberRepositoryImpl.kt, app/src/main/java/com/daily/dayo/domain/repository/MemberRepository.kt, app/src/main/java/com/daily/dayo/domain/usecase/member/RegisterFcmTokenUseCase.kt, app/src/main/java/com/daily/dayo/presentation/activity/LoginActivity.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/AccountViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/SettingNotificationViewModel.kt
+ 불필요하게 기기에 저장하던 deviceToken Shared Preference 제거
+ 필요 시 FirebaseMessaging으로 부터 현재 디바이스 토큰을 불러옴
+ 로그인 성공 시 항상 디바이스 토큰을 DB에 업데이트하고 알림 설정 여부에 따라 FCM 수신 활성화 
resolved: #440
=> #440 [feature] Change FCM Logic

app/src/main/java/com/daily/dayo/DayoApplication.kt, app/src/main/java/com/daily/dayo/common/ConvertBitmap.kt, app/src/main/java/com/daily/dayo/common/ConvertPx.kt, app/src/main/java/com/daily/dayo/common/ListLiveData.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteTagFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt, app/src/main/res/layout/fragment_write_option.xml, app/src/main/res/navigation/nav_graph.xml, app/src/main/res/values/strings.xml
- 기존에 `Fragment`에서 업로드한 이미지 리사이징 등의 작업을 하던 것을 `WriteViewModel`에서 작업하도록 변경
- 글을 업로드 하는 네트워킹 과정간에 `Dispatcher` 미설정으로 인한 `메인 스레드`를 사용하고 있던 것을 `IO 스레드`로 변경
- 글 업로드 완료 후 업로드한 글 상세보기로 넘어갈 때 기존에 `WriteFragment`로 이동한뒤 `PostFragment`로 넘어갔던 것을 `WriteOptionFragment`에서 바로 이동하도록 변경
- `WriteFragment`에서 글 업로드 완료를 Observe했던 것을 `WriteOptionFragment`에서 Observe하도록 변경
- `Bitmap`과 `File` 변환 로직, Px`로의` 변환 로직을 `Fragment`에서 작업했던 것을 `Util`로 별도 분리
- `ListLiveData`를 사용하는 경우 `Background`에서도 사용할 수 있도록 `setValue`를 사용할 것인지 여부에 대해 설정가능하도록 `ListLiveData.kt` 코드 수정 (`setValue`는 `Background 스레드`에서 사용 불가)
- `WriteOptionFragment`에서 폴더 및 태그 레이아웃이 차지하는 크기가 작아 잘 눌리지 않던 문제 `margin` 대신 `padding`을 사용하도록 설정해 좀 더 클릭하기 쉽도록 레이아웃 변경
- 기타 기능상 변경 없이 코드수를 줄일 수 있는 부분 수정
- resolved: #435
=> #435 [refactoring] Change thread networking when uploading post

app/src/main/java/com/daily/dayo/common/GlideLoadUtil.kt, app/src/main/java/com/daily/dayo/presentation/adapter/BlockListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FeedListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FolderPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/FollowListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/NotificationListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostCommentAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileBookmarkPostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileFolderListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/ProfileLikePostListAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowerListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/follow/FollowingListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/notification/NotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/block/SettingBlockFragment.kt
- Glide 사용간 'Cannot obtain size for recycled Bitmap' 예외가 발생하면서 앱이 종료되는 현상 해결
- 해당 예외는 Glide를 사용할 때 `bitmap pool`에 해당 `bitmap`이 없음에도, `recycle()` 메소드를 이용해 bitmap을 얻으려고 할 때 발생한다.
- 문제는, 해당 프로젝트에서 `bitmap.recycle()`을 호출한 적이 없음에도 해당 예외가 발생한다는 것이었다.
- 그러나, 해당 프로젝트에서 이미지를 보여주는 경우에 Glide를 활용해 Background에서 이미지를 Get한 뒤에 그 이미지를 캐시에서 찾아오는 방식으로 동작하고 있었기 때문에, 결국엔 `bitmap`이 `bitmap pool`에 없는데도 recycle하려고 하는 것과 같은 결과를 내고 있는 것으로 판단됨
- 서버로부터 받아오는 이미지 로딩과 이미지를 보여주는 경우에 분리될 필요가 없는 경우, **불필요한 Background 호출 삭제 및 직접적으로 Glide에서 load한 뒤 받아 올 수 있도록 설정**
- Home 탭과 같이 미리 로드되는 이미지가 존재해, 서버와의 통신과 이미지를 보여주는 시기의 차이가 존재하는 경우, 기존의 Background에서 로드한 뒤 해당 bitmap을 이용하는 로직을 유지하되, bitmap pool에서 해당 bitmap이 로드한 뒤 이미지 뷰를 통해 이미지를 보여주기 전에 삭제돼 이미지 뷰에서 bitmap을 정상적으로 로딩하지 못하는 경우 bitmap을 다시 서버에서 받아올 수 있도록 `try ~ catch` 예외 처리 추가
- 추가적으로 …
=> [bug] Fix glide exception `Cannot obtain size for recycled Bitmap`

app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/SearchViewModel.kt, app/src/main/res/layout/fragment_search.xml, app/src/main/res/layout/fragment_search_result.xml, app/src/main/res/layout/item_search_result_post.xml
+ RecyclerView의 마지막 아이템이 잘리는 문제 수정
+ `SearchFragment`에 빠져있던 `onDestroyBindingView` 추가
+ 기존에는 `SearchFragment`와 `SearchResultFragment`사이에 검색 키워드를 navigation args로 전달했음
+ 이때, 다른 키워드로 검색 후 뒤로가기를 통해 다시 `SearchResultFragment`로 접근하면 
가장 처음에 전달된 키워드로 검색하는 문제 발생
+ 따라서 args를 제거하고 ViewModel을 통해 검색 키워드를 저장하도록 변경
resolved: #443
=> #443 [layout] SearchResultFragment RecyclerView

app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt
- 게시글 상세보기로 이동한 뒤 뒤로가기를 통해 글 목록으로 다시 돌아온 경우 이전의 스크롤이 유지되도록 설정
- 기본적으로 저장되도록 설정되어 있으나, 홈화면에 해당하는 Dayo Pick과 New의 경우만 그 설정이 유지되지 않아 `stateRestorationPolicy` 설정 추가
- `savedInstanceState`의 값을 확인해 null로 확인되면 Fragment 최초 로딩으로 간주해 게시글 리스트를 받아올 수 있도록 처리 이외의 경우에는 Referesh하는 경우에만 게시글 목록을 갱신하도록 처리
- ProfileFragment, NotificationFragment 의 경우 별도의 사전 처리 과정에 의해 현재 미구현 상태
- resolved: #458
=> [bug] Scroll position not saved when returned from Post Fragment

app/src/main/java/com/daily/dayo/presentation/fragment/feed/FeedFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/post/PostFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/search/SearchResultFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/HomeViewModel.kt
- 카테고리를 변경하거나 탭을 변경하는 등 글 목록이 갱신되는 경우에 자동으로 최상단으로 이동하는 기능 추가
- `onCreate()`에서도 게시글을 불러오는 동일한 메소드를 사용하므로, Lifecycle State에 따라 이동할 수 있도록 추가 구현
- resolved: #460
=> [feature] Add Auto scroll to the top when refresh the post

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/com/daily/dayo/presentation/activity/MainActivity.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeDayoPickAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/HomeNewAdapter.kt, app/src/main/java/com/daily/dayo/presentation/adapter/PostImageSliderAdapter.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/setting/notification/SettingNotificationFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/res/values/strings.xml
- 기존 `compileSDK`및 `targetSDK`가 31로 되어있던 부분 33으로 조정
- Android 33으로 넘어가면서 변경된 권한 적용
- 기존 옵트아웃이였던 알림 권한이 옵트인으로 적용됨에 따라 알림을 요청하는 기능에 대해 MainActivity에서 명시적으로 요청하도록 구현
- 알림에 대해 아무런 설정을 하지 않거나 거부한 경우 새로 앱을 시작하는 경우 혹은 앱 내부의 알림 설정 페이지로 들어가는 경우에 알림 허용에 대한 메시지를 보여줄 수 있도록 구현
- 알림을 허용한 경우에만 서버에서 알림을 보내줄 수 있도록 설정하는 request를 보내도록 구현
- 기존 사진 및 카메라 권한에 대한 세부화에 따른 요청 권한 추가 명시 및 이전 버전과의 분기 처리 추가
- 해당하는 페이지들에 대해 Android SDK 33 이전과 이후로 분기처리해 권한을 요청할 수 있도록 수정
- resolved: #466
=> [feature] Apply changes as update to Android SDK 33

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/res/values/strings.xml
+ 기존 닉네임과 동일할 시 닉네임 중복 체크를 하지 않고, 완료 버튼이 활성화되도록 변경
resolved : #475
=> #475 [bug] Don't validate when keeping nickname

app/build.gradle, app/src/main/AndroidManifest.xml, build.gradle, gradle/wrapper/gradle-wrapper.properties
- 언어 및 Gradle, JVM, 라이브러리 의존성 관련 버전 최신화를 위한 작업
- 기존 Kotlin 버전을 1.6.0에서 1.8.20로 업데이트
- Kotlin Version이 1.8.20으로 업데이트됨에 따라, Compose Compiler Version을 1.4.6으로 설정
- [Pre-release Kotlin Compatibility](https://developer.android.com/jetpack/androidx/releases/compose-kotlin#pre-release_kotlin_compatibility)
- Android Gradle Plugin(AGP) 버전을 8.1로 변경
- 현재 Stable Version이 발표된 [Android Studio Giraffe가 3.2~8.1만 지원](https://developer.android.com/build/releases/gradle-plugin)함에 따라 8.2가 아닌 8.1로 설정
- gradle distributionUrl 8.1로 변경
- 기존 사용하던 JDK 1.8에서 17로 변경
- JetBrains Runtime Version 17 사용
- Build.gradle에서 기존에 1.8로 수동으로 JVM 타겟 지정했던 것을 변경
- 이외 관련에러가 지속적으로 발생함에 따라 jvmToolChain(17) 추가
- [Unable to set kapt jvm target version](https://youtrack.jetbrains.com/issue/KT-55947/Unable-to-set-kapt-jvm-target-version# …
=> [chore] Update kotlin, dependency, JVM version

app/src/main/java/com/daily/dayo/common/image/ImageResizeUtil.kt, app/src/main/java/com/daily/dayo/common/image/ImageUploadUtil.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/account/signup/SignupEmailSetProfileImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileEditImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/write/WriteImageOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/WriteViewModel.kt, app/src/main/res/values/strings.xml
- 지원하지 않는 확장자를 가진 이미지 파일이 업로드 되는 문제 해결
- 이미지 관련 Extension 등이 존재하는 패키지 생성
- jpg, jpeg, png, webp의 확장자를 가진 이미지 파일만 업로드할 수 있도록 구현
- 관련 확장함수를 구현해 이미지를 업로드 하는 곳에서 공통적으로 사용
- 이미지 확장자가 맞지 않는 이미지 업로드 시도시 경고 토스트 출력
- 업로드하려고 하는 이미지가 5장 이상인 경우 이미지 확장자가 맞지 않는 이미지를 제외하고 나머지에 대해 업로드하기 위해 업로드 개수를 카운팅하는 로직 변경
- resolved: #485
=> [bug] Fix image with unsupported extensions being uploaded.

app/src/main/java/com/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt
- 좋아요 버튼을 누르는 경우 스크롤이 최상단으로 이동하는 문제
- LoadingView를 멈추는 경우에 스크롤을 최상단으로 이동시키는 코드가 해당 문제의 원인으로 파악후 제거
- resolved: #487 
- #463
=> [bug] Fix scrolling to the top 

app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderOptionFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/folder/FolderSettingAddFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, app/src/main/java/com/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/FolderViewModel.kt, app/src/main/java/com/daily/dayo/presentation/viewmodel/ProfileViewModel.kt, app/src/main/res/layout/fragment_my_page.xml, app/src/main/res/layout/fragment_profile.xml, app/src/main/res/navigation/nav_graph.xml
- Profile 페이지에서 폴더를 들어가고 나올때, 유저정보가 나타나는 collapsingLayout에 대한 스크롤이 유지되지 않고 있던 현상에 대해 `requestApplyInset`을 통해 해결
- Profile 페이지에서 보여지는 Folder ListView에 대해서 Profile View가 Destroy될 때 folder에 대한 정보와 유저에 대한 정보를 null 처리하여 다른 사람의 프로필 페이지르 들어갈 때 이전에 본 사람의 정보가 일시적으로 보여지고 있던 현상 해결
- 해당 과정에서 기존에 사용하고 있던 Data에 대해 Resource로 Wrapping 처리
- 폴더 삭제후, 마이페이지가 아닌 다른 사람 프로필을 보는 Fragment로 이동하고 있던 현상 수정
- 삭제 완료후 마이 페이지로 이동할 수 있도록 설정
- folderAccess에 대한 오타를 folderSuccess로 수정
- resolved: #495
=> [bug] Fix updated folder is not refreshed and displayed other user's information

presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt, presentation/src/main/java/daily/dayo/presentation/fragment/feed/FeedFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeDayoPickPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/home/HomeNewPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/MyPageFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/notification/NotificationFragment.kt
- Bottom Naviagtion Bar에서 현재 위치한 페이지에 대한 Icon을 클릭하는 경우, 스크롤을 최상단으로 이동시키면서 새로고침 기능 추가
- ViewPager 내부에 Fragment가 있는 경우 다른 탭이 선택되어있어 Fragment가 보이지 않음에도 아이콘을 클릭했을 때, 새로고침되는 현상을 방지하기 위해 ClickListener를 LifeCycle이 RESUME 상태일때 설정하고 PAUSE 상태가 되는 경우 해제되도록 구현
- 최상단으로 이동하는 겨웅 Smooth Scroll 되도록 구현
- SwipeRefreshLayout이 존재하는 경우, 해당 레이아웃이 새로고침될 때 나타나도록 구현
- MyPage에서 CollapsingToolbarLayout에 대해서 접혀있는 경우에 해당 레이아웃도 펼쳐지도록 구현
- resolved: #500
=> [feature] Add Refreshing when bottom navigation bar icon is clicked

.github/workflows/android-ci.yml, app/build.gradle
- Develop Branch에 Pull Request를 보내는 경우에 대해 자동으로 빌드 및 테스트가 실행시켜 정상적으로 통합되는지에 대해 검사
- Keystore에 대해 기존에 gradle.properties를 통해 관리하던것을 keystore-release.properties로 별도 분리
- release에 대한 keystore 파일의 명확한 이름 설정
- 업로드가 불가능한 파일및 코드들에 대해서 repository secrets로 관리
- resolved: #509
=> [feature] Create Android CI

app/proguard-rules.pro
- Release버전에서 Retrofit과 관련되어 난독화 진행시 Crash가 발생함에 따라, 관련된 코드에 대해 난독화 제외 처리
- 모듈화하면서 정상적으로 난독화 제외되었던 파일이 제외되지 않고 있던 부분에 대해, 제외될 수 있도록 처리
- https://github.com/square/retrofit/issues/3751#issuecomment-1515817159
- resolved: #511
=> [bug] Add code to exclude obfuscation related to networking

presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileBookmarkPostListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileFolderListFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileLikePostListFragment.kt
+ 게시글에서 내 프로필로 이동 시 앱이 종료되는 현상에 대한 처리
+ 바텀네비게이션이 Reselected되는 상황이 아닐 때 `currentViewPagerPosition`이 null이어서 발생한 문제였음
+ null 값에 대한 처리 또는 Reselected시에만 view pager의 position을 불러오는 방법 중 `setBottomNavigationIconClickListener` 메소드의 의미에 맞게 후자의 방법으로 수정
+ 코드 정렬로 인한 코드 라인 변경
resolved: #513
=> #513 [bug] Error when navigating to My Profile

.github/workflows/Android-release CI.yml
- Gradle caching 과정에서 더이상 지원되지 않는 오픈소스 제거 및 새로운 버전으로 업데이트
- 캐싱작업을 Branch 체크아웃 하자마자 JDK 및 SDK 설치 등의 다른 작업들이 실행되기 이전에 체크하도록 순서 변경
- CI 작업에 대한 release 및 debug 버전 구분을 위한 파일 이름 명확화
- resolved: #518
=> [bug] Gradle caching is no longer valid in CI

app/src/main/AndroidManifest.xml, presentation/src/main/java/daily/dayo/presentation/activity/LoginActivity.kt, presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt
- LoginActivity및 MainActivity에서 디바이스에서의 Back Button을 누르는 동작을 가로채 `popBackStack()` 동작이 이뤄지도록 설정
- backStackEntry의 개수를 확인해 backStack에 아무것도 없으면 앱이 종료되도록 설정
- 기존에 페이지간 트랜지션이 완료되기 이전에 시스템의 Back Event가 또 다시 발생하면 정상적으로 `popBackStack()`이 동작하지 않던점을 오버라이드가 되도록 설정해 해결
- AndroidManifest에서 enableOnBackInvokedCallback에 대해 true 설정
- API 33이상을 지원하는 경우 해당 속성을 true로 설정해야 시스템의 Back Event를 가로챌 수 있음에 따라 설정
- resolved: #520
=> [bug] Override system back button press action

app/build.gradle, presentation/build.gradle, presentation/src/main/java/daily/dayo/presentation/view/FilledTextField.kt
+ 요구 사항에 따라 공통적으로 사용할 FilledTextField만들기
+ Icon도 변경할 수 있어야합니다.
+ 위의 모든 상황에 대해 설정할 수 있도록 했습니다. 
+ Material Icon 라이브러리를 추가했습니다
```kotlin
@Composable
fun FilledTextField(
value: String,
onValueChange: (String) -> Unit,
label: String = "",
placeholder: String = "",
isError: Boolean = false,
errorMessage: String = "",
trailingIcon: (@Composable () -> Unit)? = null,
textAlign: TextAlign = TextAlign.Left
) 
``` 
- value, onValueChange만 필수 매개변수
- trailingIcon설정으로 우측 아이콘을 설정할 수 있음
```kotlin
@Composable
fun FilledPasswordField(
value: String,
onValueChange: (String) -> Unit,
label: String = "",
placeholder: String = "",
isError: Boolean = false,
errorMessage: String = "",
textAlign: TextAlign = TextAlign.Left
) 
```
- value, onValueChange만 필수 매개변수
- Figma상에 이미지는 없지만 password 입력 시 별도로 text가 숨겨져야하므로 …
=> [layout] Common Text Fields

presentation/src/main/java/daily/dayo/presentation/view/TopNavigation.kt
+ 공통적으로 사용할 Top Navigation 만들기
+ 타이틀 텍스트를 왼쪽 혹은 오른쪽 정렬 가능
+ 피그마에 왼쪽과 오른쪽 각각 아이콘을 하나만 적용하는 경우만 존재하므로 하나씩만 적용할 수 있도록 함
+ Material3 사용을 위해 `@OptIn(ExperimentalMaterial3Api::class)` 어노테이션을 추가
```Kotlin
@Composable
fun TopNavigation(
title: String = "",
leftIcon: @Composable () -> Unit = {},
rightIcon: @Composable () -> Unit = {},
titleAlignment: TopNavigationAlign = TopNavigationAlign.LEFT
) 
```
**참고 사항**
+ title은 h3 폰트 스타일 적용
+ title 텍스트 위치가 왼쪽이나 중간에만 올 수 있으므로 enum클래스를 사용해 다른 속성을 입력할 수 없도록 함 
```Kotlin
enum class TopNavigationAlign {
LEFT, CENTER
}
```
resolved: #533
=> #533 [layout] Common Top Navigation

presentation/src/main/java/daily/dayo/presentation/view/Button.kt
```kotlin
@Composable
fun OutlinedButton(
onClick: () -> Unit,
label: String,
icon: @Composable (() -> Unit)? = null,
size: Size? = null
)
```
```kotlin
@Composable
fun FilledButton(
onClick: () -> Unit,
label: String,
icon: @Composable (() -> Unit)? = null,
enabled: Boolean = true,
isTonal: Boolean = false,
size: Size? = null
) 
```
**참고 사항**
+ fully rounded corners 형태의 버튼입니다.
+ 아이콘은 텍스트 왼쪽에 표시됩니다.
+ isTonal 속성 
material3문서에서 연한 배경색의 버튼을 tonal button이라 하고 있습니다. ((처음 알게된 사실..)
<p> <img width="500" alt="image" src="https://github.com/Daily-DAYO/DAYO_Android/assets/30407907/6d04c5be-b39b-47ff-9063-e84accabffc6"> </p>
문서 (https://m3.material.io/components/buttons/overview) </br>
</br>
Figma에 있는 연한 색상의 배경 버튼을 지정하고 싶을 때는 isTonal로 설정하면됩니다.
```kotlin
@Composable
fun FilledRoundedCornerButton( …
```
=> #535 [layout] Common Buttons

presentation/src/main/java/daily/dayo/presentation/view/Chip.kt
```kotlin
@Composable
fun Chip(
modifier: Modifier = Modifier,
onClickChip: (() -> Unit) = {},
text: String,
color: Color = PrimaryGreen_23C882,
enabled: Boolean = true
)
```
**참고 사항**
+ color 설정 시 text와 border색상이 동일하게 적용됩니다.
+ disabled 상태에는 설정된 색상과 무관하게 글자와 border 모두 회색으로 표시됩니다. 
resolved: #536
=> #536 [layout] Common Chip

presentation/build.gradle, presentation/src/main/java/daily/dayo/presentation/view/BottomSheetDialog.kt
- 공통으로 사용할 BottomSheetDialog Component 구현
- Compose로 구현할 기본적인 뷰와, BottomSheetDialog가 겹쳐서 보일 수 있도록, Box로 가장 바깥족에 선언해 사용할 수 있습니다
- BottomSheetDialog사용을 위해 1개의 BottomSheetDialog마다, 1개의 bottomSheetDialogState를 선언해준뒤 이를 BottomSheetDialog를 생성할때 주입해야 합니다
- Category 레이아우셍서 buttons의 텍스트와 leftIconButtons의 이미지의 인덱스는 동일해야 합니다
- #539
=> [layout] Add Common BottomSheetDialog Component

presentation/src/main/java/daily/dayo/presentation/view/BottomSheetDialog.kt
- BottomSheetDialog 크기가 실행 기기의 height의 절반이상 커지지 못하는 문제 해결
- 기존에 BottomSheetDialog State를 초기화하면서, disableFullExpanded값이 true, skipHalfExpanded값이 false로 설정되어 있어, 커지지 못하고 있던 부분에 대해 기본값 수정해 Bug Fix
- #548
=> #548 [bug] bottomSheetDialog does not expand more than half of the screen

presentation/src/main/java/daily/dayo/presentation/activity/MainActivity.kt, presentation/src/main/java/daily/dayo/presentation/screen/feed/FeedScreen.kt, presentation/src/main/java/daily/dayo/presentation/view/CategoryHorizontalGroup.kt, presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/FeedViewModel.kt, presentation/src/main/res/drawable/ic_bookmark_checked.xml, presentation/src/main/res/drawable/ic_bookmark_default.xml, presentation/src/main/res/drawable/ic_comment.xml, presentation/src/main/res/drawable/ic_hashtag.xml, presentation/src/main/res/drawable/ic_heart_filled.xml, presentation/src/main/res/drawable/ic_heart_outlined.xml, presentation/src/main/res/values/strings.xml
+ 피드 상단 카테고리 가로 스크롤 구현
+ 표시할 게시글이 없을 때 표시 할 Empty View 구현
+ 팔로우하러 가기 버튼을 누르면 홈으로 이동
+ 이미지가 여러개일 시 스크롤 할 수 있도록 Pager 구현
+ 좋아요, 북마크 기능 
+ 좋아요, 댓글 개수가 0일 때와 아닐 때 색상 구분
+ 게시글 텍스트가 2줄 이상이면 더보기버튼이 나타나도록 함
+ 태그를 # 아이콘과 함께 나타내며, 가로로 스크롤 할 수 있도록 구현 
+ 카테고리 별로 다른 리스트로 보여주는 기능은 API 추가 후 구현 예정
+ 옵션 버튼 클릭 기능은 디자인이 나온 후 구현 예정 
resolved : #546
=> #553 [layout] Feed Screen

app/build.gradle, app/src/main/AndroidManifest.xml
- Debug와 Release에 대해 BuildType의 구분을 활용해 Build Varient를 변경할때, 별도의 앱으로 설치될 수 있도록 설정
- Debug의 경우 패키지명이 suffix로 뒤에 추가됨에 따라, 새로운 `google-services.json`로 교체 필요
=> [refactoring] Separate App with build type

presentation/src/main/java/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordCompleteFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/account/findAccount/FindAccountPasswordNewPasswordFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/mypage/profile/ProfileEditFragment.kt, presentation/src/main/java/daily/dayo/presentation/fragment/setting/changePassword/SettingChangePasswordCurrentFragment.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/AccountViewModel.kt, presentation/src/main/res/layout/fragment_find_account_password_check_email.xml, presentation/src/main/res/layout/fragment_find_account_password_check_email_certificate.xml, presentation/src/main/res/layout/fragment_find_account_password_complete.xml, presentation/src/main/res/layout/fragment_find_account_password_new_password.xml, presentation/src/main/res/layout/fragment_find_account_password_new_password_confirmation.xml, presentation/src/main/res/layout/fragment_login_email.xml, presentation/src/main/res/layout/fragment_profile_edit.xml, presentation/src/main/res/layout/fragment_setting_change_password_current.xml, presentation/src/main/res/layout/fragment_setting_change_password_new.xml, presentation/src/main/res/layout/fragment_signup_email_set_email_address.xml, presentation/src/main/res/layout/fragment_signup_email_set_email_address_certificate.xml, presentation/src/main/res/layout/fragment_signup_email_set_password.xml, presentation/src/main/res/layout/fragment_signup_email_set_password_confirmation.xml, presentation/src/main/res/layout/fragment_signup_email_set_profile.xml
+ 정보 입력 과정에서 키보드에 스크롤뷰를 적용해 edit text가 가려지는 부분 수정
+ 회원가입 화면
+ 로그인 화면
+ 로그인 시 비밀번호 재설정 화면
+ 프로필의 비밀번호 재설정 화면
+ 프로필 수정 화면
+ 비밀번호 재설정 과정에서 화면 전환이 제대로 되지 않는 문제 해결
+ 프로필 비밀번호 재설정 화면에서 현재 비밀번호 확인 시 Event wrapper를 적용해 확인 값이 지속적으로 사용되지 않도록 함
+ 프로필 비밀번호 재설정 로직 변경
+ 입력 중에는 비밀번호 검증을 하지 않도록 변경
resolved: #332 , #568
=> [layout] Fix Setting User Information

presentation/src/main/java/daily/dayo/presentation/adapter/SearchTagResultPostAdapter.kt
- 검색결과 아이템의 Width, Height에 대한 값이 invisible 처리됨에 따라 값이 정상적으로 계산되지않아, 비정상적인 값으로 이미지뷰가 오버라이드되면서 검색결과가 보이지 않던 문제에 대한 해결
- 기존 이미지뷰의 width와 height로 오버라이드 하던부분을 다시 홈의 썸네일과 동일하게 상수로 오버라이드 하도록 원복
- #581
=> Fix Search Result invisible

presentation/src/main/java/daily/dayo/presentation/view/TextField.kt
+ 공통으로 사용하는 TextField에 대한 keyboardOptions 및 keyboardActions을 param으로 받아 지정할 수 있도록 param 추가
+ TextField에 대한 enable/diable 처리를 외부에서 지정할 수 있도록 param 추가
resolved: #609
=> [feature] Add KeyboardOptions, actions, and disable textField feature

presentation/src/main/java/daily/dayo/presentation/common/image/ImageUploadUtil.kt
- 기존 사진 선택시 갤러리 및 카메라 호출에 대한 처리를 각 Composable function 내부에서 처리함으로써 처리 로직이 상이한 문제 제거
- 권한 허용 및 미디어(갤러리/카메라) 로드에 대한 로직은 시스템 종속적이므로 중복코드 발생이 필연적이므로 이를 공통화 처리
- 갤러리 및 카메라 로드시 `launchGallery` `launchCamera`를 통해 호출할 수 있도록 구현
- 미디어 관련 권한 허용 요청상태에서 권한 허용시 바로 미디어가 보여질 수 있도록 처리
- 선택/촬영한 이미지에 대한 로직과 권한 미허용시에 대한 action은 이를 호출하는 composable function에서 처리할 수있도록 구현
- 현재 단일 사진에 대한 갤러리 호출만 가능한 상태로, 추후 여러장의 사진에 대한 갤러리 호출 function 추가 예정
- 갤러리 이미지 선택에 대한 UI 개선 여부에 따라서 추후 메소드 내부 동작은 변경될 수 있으나, 전체적인 interface는 유지
=> [feature] Add composable function for single photo selection via gallery/camera

presentation/src/main/java/daily/dayo/presentation/screen/mypage/MyPageEditScreen.kt, presentation/src/main/java/daily/dayo/presentation/view/RoundImageView.kt, presentation/src/main/java/daily/dayo/presentation/view/dialog/CommentBottomSheetDialog.kt
- AsyncImage 사용시, model에 placeholder/error를 포함시켜 로드했던 것에 대해 AsyncImage의 parameter에 넣도록 분리
- 기존 RoundImageView 사용시 placeholder parameter type이 Drawable이었던것에 대해 Drawable Id를 전달하도록 변경
- 이에 영향 받는 내프로필 변경 뷰와 댓글 바텀시트 뷰에 대한 변경
- 기존 BadgeRoundImageView에서 imageUrl에 대해 String으로 받고있던 것에 대해 Any 타입으로 변경해 여러 타입을 받아올 수 있도록 설정
- #616
=> [bug] Change Image placeholder/error parameter

presentation/src/main/java/daily/dayo/presentation/view/dialog/ConfirmDialog.kt
- Confirm, Cancel 버튼에 대한 텍스트 변경이 가능하도록 parameter 추가
- onClickCancel이 없는 상황에 대해 null로 설정 할 수도록 처리해, onClickConfrim만 보이는 단순 알림 Dialog에서 사용 가능하도록 처리
- 기존 Dialog가 Dismiss되는 경우 onClickCancel이 호출되도록하는 것은 유지하되, onClickCancel이 null인 경우 onClickConfirm이 호출되도록 처리
- onClickConfirm은 non-nullable처리를 통해 버튼이 모두 없는 Dialog가 되지 않도록 처리 (ConfirmDialog 네이밍과 맞지않음)
- title 혹은 description의 text가 blank인 경우 view를 그리지 않도록 처리해, 불필요한 공백 등이 보이지 않도록 처리
- #628
=> [feature] Add customizable button texts, null cancel handling, and condional view rendering

presentation/src/main/java/daily/dayo/presentation/view/Button.kt
- 기존 FilledRoundCornerButton에 대해 radius 조절이 불가능했던 것에 대해 radius parameter 추가로 조절할수 있도록 변경
- #636
=> Add radius parameter to FilledRoundedCornerButton

presentation/src/main/java/daily/dayo/presentation/screen/home/HomeDayoPickScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/home/HomeNewScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/home/HomeScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/HomeViewModel.kt
- 홈 화면에서 게시글이 깜빡이는 문제 발생
| 피드 전환 | 카테고리 버튼 클릭 시 |
|--|--|
|![May-21-2025 16-30-55](https://github.com/user-attachments/assets/45b21144-d361-4e58-92bb-ed2ac1d99300)|![May-21-2025 16-31-14](https://github.com/user-attachments/assets/e73791c4-2a1e-4cdd-9c1d-474538d0535b)|
- LaunchedEffect를 사용해 카테고리가 변경될 때만 게시글을 호출하도록 변경
- 카테고리 버튼 클릭 시 동작을 홈에서 설정하도록 변경 
- resolved : #647
=> Prevent home screen flickering

README.md, app/build.gradle, build.gradle, data/build.gradle, presentation/build.gradle, presentation/src/main/java/daily/dayo/presentation/screen/settings/SettingsScreen.kt, presentation/src/main/java/daily/dayo/presentation/view/Button.kt, presentation/src/main/java/daily/dayo/presentation/view/Chip.kt, presentation/src/main/java/daily/dayo/presentation/view/Comment.kt, presentation/src/main/java/daily/dayo/presentation/view/DetailPostView.kt, presentation/src/main/java/daily/dayo/presentation/view/FeedPostView.kt, presentation/src/main/java/daily/dayo/presentation/view/HomePostView.kt
- Compose 라이브러리 버전 업데이트 및 업데이트간 Deprecated된 API 메소드들에 대한 리팩토링
- ripple 관련 코드 변경
- Chip-border 설정 코드 변경
- Compose 라이브러리 버전 업데이트로 인한 compileSdk 35로 상향
- #645
=> Update Compose and compileSdk version, migrate deprecated APIs

presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/search/SearchNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt
- 최초 키워드 검색 이후, 타 키워드 검색후에도 상세페이지로 이동후 검색결과 화면으로 돌아오는 경우 항상 최초 키워드 검색화면이 표시되는 현상 해결
- 검색결과 이동시에 searchKeyword를 이용해 route를 설정해 이동하는데, 최초 키워드 검색 이후 이를 갱신하지 않아서 생기는 문제에 대한 해결
- Composable 내부에서 viewmodel의 searchKeyword 함수만 호출함에따라, NavBackStackEntry의 param searchkeyword는 그대로 남아있고, 상세페이지에서 돌아가는 경우 다시 그 값으로 recomposition 되기 때문에 발생했던 문제
- 기존에 viewModel을 이용해 검색 결과를 갱신하던 방식에서 기존의 route에 searchKeyword를 설정하는 방식을 활용해, 검색할때마다 route인자를 변경해 화면전환을 통해 결과값을 보여주고, 직전 키워드 검색 화면은 Stack에서 제거함으로써 해결
- #660
=> Fix showing initial search result when navigating back from later searches

presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
- MainBottomNavigation의 레이아웃을 figma디자인에 맞게 변경
- Preview추가 
- Compose버전 변경 이후 불필요한 OptIn어노테이션 (ExperimentalMaterialApi) 제거 
- resolved : #665
=> Fix MainBottomNavigation layout

presentation/src/main/java/daily/dayo/presentation/screen/search/SearchResultScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/search/SearchScreen.kt, presentation/src/main/res/values/strings.xml
- 최근 검색어가 없는 경우에 대한 Empty view 추가
- #656
=> Add Search history empty view

presentation/src/main/java/daily/dayo/presentation/view/dialog/NetworkErrorDialog.kt, presentation/src/main/res/values/strings.xml
- 기존 `ConfirmDialog`를 이용해 Network Error Dialog 구현
- 별도의 레이아웃 변경사항이 없는한 onClickRetry만 호출할 네트워킹 작업에 넣으면 됨
- #672
=> Add Network Error Dialog layout

presentation/src/main/java/daily/dayo/presentation/screen/post/PostScreen.kt, presentation/src/main/java/daily/dayo/presentation/view/Comment.kt, presentation/src/main/java/daily/dayo/presentation/view/dialog/CommentBottomSheetDialog.kt
- 댓글 작성 완료 시 키보드 숨기기
- 공백으로만 댓글 작성 막기
- 디자인 수정에 따라 댓글 텍스트 스타일 변경
- 댓글 다이얼로그를 숨기면 키보드도 숨기기
- 컴포즈 버전 변경에 따라 텍스트필드 스타일 고치기 
- resolved: #667
=> Fix layout of comment section

app/src/main/AndroidManifest.xml, presentation/build.gradle, presentation/src/main/java/daily/dayo/presentation/common/image/ImageOrientationUtil.kt, presentation/src/main/java/daily/dayo/presentation/common/image/ImageSamplingUtils.kt, presentation/src/main/java/daily/dayo/presentation/screen/write/ImageCropScreen.kt, presentation/src/main/java/daily/dayo/presentation/screen/write/ImageCropStateHolder.kt, presentation/src/main/java/daily/dayo/presentation/screen/write/WriteNavigation.kt, presentation/src/main/java/daily/dayo/presentation/screen/write/WriteScreen.kt, presentation/src/main/java/daily/dayo/presentation/viewmodel/WriteViewModel.kt, presentation/src/main/res/drawable/ic_crop.xml, presentation/src/main/res/values/strings.xml
- 업로드 이미지 편집기능 내재화
- 대용량 이미지 로드 대응
- 의도치 않은 이미지 방향 오류 발생 해결
- Third-party cropper library 제거 및 Compose 기반의 인앱 이미지 편집 기능 구현
- 대용량 이미지 로드간 OOM 방지 처리
- EXIF 정보를 활용해 이미지 로드시, 유저의 의도와 달리 회전되어있는 경우 유저 입장에서 정상적으로 보이도록 이미지 처리
- Write 관련 state에 대해 lifecycle에 맞게 유지되도록 변경
- 크롭 이미지 영역 지정시 정사각형 형태의 그리드 형태로 구현
- 크롭 이미지 영역 지정시 두 손가락으로 조작하는 Pinch-Zoom 제스처와 한 손가락으로 사각형의 각 4개의 모서리로 영역을 조작하는 제스처를 통한 영역 지정 제스처 구현
- 최소 이미지 처리 추가
- 크롭 진행간 제스처 겹침 및 이미지뷰 외부 영역으로 영역 벗어남 등에 대한 예외 처리 적용
- 관련 ImageAsset 등의 데이터 클래스 등을 활용해 크롭 상태 관리 처리
- 이외 지정 영역에 대한 그리드 및 shadow 등 UI 개선
- 업로드 이미지 로드에 대해 이미지 로드이전 이미지 정보를 미리 읽고 inSampleSize를 개선해 기기에 최적화된 디코딩을 통한 OOM 방지 처리
- `inJustDecodeBounds = true/false`
- 글 작성화면 및 이미지 편집화면 진입시 이미지 로드간 비동기적 로드를 통해 OOM 방지처리
- 업로드 시점에만 서버와 미리 지정한 사이즈로 리사이징 및 파일포맷 변환, 업로드 처리 이후 관련 메모리 해제 처리로직 추가
- 편집 완료 …
=> Update Image Upload Flow

presentation/src/main/java/daily/dayo/presentation/screen/main/MainScreen.kt
- 바텀시트가 올라올 때 배경이 어두워지지 않는 문제 해결
- BottomSheetScaffold는 기존의 ModalBottomSheet와 달리 dim 효과가 나타나지 않기 때문에 생긴 문제였음
- BottomSheet의 상태에 따라 직접 어두운 배경을 보여주도록 수정 (0.6f는 Figma의 디자인에 따라 지정한 값입니다.)
- 이때, alpha값을 애니메이션 처리 
- resolved : #683
=> Add animated dim background for BottomSheet
